package com.example.menutest.addword;

import com.example.menutest.MainApplication;
import com.example.menutest.bean.Word;
import com.example.menutest.database.WordDao;

/**
 * Created by Administrator on 2017/5/5.
 */

public class AddWord {


    WordDao dao=new WordDao(MainApplication.getContext());

    public void testAdd(){

        dao.add(new Word("0","resolve","/rɪ'zɑlv/","n.决心\nv. 解决，决定，分解","Nothing shakes his resolve of being a fluent English speaker!\n没有什么能动摇他的决心--成为流利讲英语的人！","[串记] absolve 免罪\ndissolve 溶解\ndissolute 放荡\nresolve 解决、决心、溶解\nresolute 坚决的","0"));
        dao.add(new Word("1","apart","/ə'pɑːt/","adj. 客观的；目标的；宾格的\nn. 目的；目标；[光] 物镜；宾格","They set one man apart from the rest.\n他们把一个人从人群里分离出来了。","[串记] apartment n.公寓，房间\nparty n.聚会，派对，政党，当事人\ndepart v.离开，偏离\npartly a.部分的，一定程度上","0"));
        dao.add(new Word("2","objective","/əb'dʒektɪv/","adv. 相距；与众不同地；分离着\nadj. 分离的；与众不同的","My objective this year is to lose weight!\n我今年的目标是减肥！","[串记] object n.物体对象，v.反对\nobjective a.客观的，n.目标，目的\nobjection n.反对\nsubjective\nobject to 反对","0"));
        dao.add(new Word("3","local","/'ləʊk(ə)l/","n. [计] 局部；当地居民；本地新闻\nadj. 当地的；局部的；地方性的；乡土的","The local people have their own clothing and culture.\n当地人有自己的服装和文化","[对比] local偏重于地区性，local accent就是指地方口音。\nnative则更多偏重于国家范围，native speaker 仅仅表示母语是某种语言的人，而并非指所有说这种语言的人，可见有很强的国家性质。","0"));
        dao.add(new Word("4","generous","/'dʒen(ə)rəs/","adj. 慷慨的，大方的；宽宏大量的；有雅量的","The generous man distributes lucky money to us during each Spring Festival.\n这个大方的男人每年春节都给我们发红包。","[联想] gentleman（绅士）都很generous（慷慨）。","0"));
        dao.add(new Word("5","chew","/tʃuː/","n. 咀嚼；咀嚼物\nvt. 嚼碎，咀嚼\nvi. 细想，深思","Chew your food well before you swallow it.\n食物在吞咽前要仔细咀嚼。","[联想] “触”：咀嚼（chew）食物要用舌头碰触。\ncrew n.全体船员","0"));
        dao.add(new Word("6","behalf","/bɪˈhæf/","n. 代表；利益","My wife could not be here tonight, but I want to thank you on her behalf.\n我的妻子今晚因故不能前来， 我谨代表她向你们致谢。","[联想] 代表别人，就是半个","0"));
        dao.add(new Word("7","treat","triːt/","vt. 治疗；对待；探讨；视为\nn. 请客；款待","I went to the dentist's office to get my teeth treated.\n我去牙医那里治疗我的牙齿。","[对比] cure/treat/heal/remedy都有“治疗、医治”之意，区别是：\ncure：主要指治愈疾病。\ntreat：普通用词，指接受并诊治病人。\nheal：侧重于治愈伤口、伤痛如灼伤等。\nremedy：着重用药物对病人进行治疗。","0"));
        dao.add(new Word("8","transfer","/ˈtrænsfər/","n. 转让；转移；传递；过户\nvi. 转让；转学；换车\nvt. 使转移；调任","The worker transferred the box to another place.\n工人把箱子转移到另一个地方。","[串记] transaction n.交易\ntransform v.改变\ntransfer v.转移，调职\ntransition n.过渡\ntransmit v./n.运输","0"));
        dao.add(new Word("9","acknowledge","/əkˈnɑlɪdʒ/","vt. 承认；答谢；报偿；告知已收到","\"Darling,I'm pregnant.Please acknowledge this text.\".\n“亲爱的，我怀孕了，收到请回复。”","[对比] acknowledge：通常指公开承认某事的真实情况或自己的过错。\nadmit：强调因外力或良心驱使或经判断而明确承认，多含不情愿或被迫意味。\nconfess：语气较重，着重承认自己意识到的错误或罪行，含坦白忏悔的意味。\n","0"));
        dao.add(new Word("10","estate","/ɪˈsteɪt/","n. 房地产；财产；身份","My estate includes my house and part of the forest.\n我的地产包括我的房子和这片森林的一部分。","[串记] state n.州，事态，说\nstatement n.陈述\nunderstatement n.（往下面说，不敢说太多，话不要说太满）保守地说\noverstate vt.（往上面吹嘘）夸大其词\nestate n.（e-/ex-表示外面的意思；在土地外面的房子）房地产","0"));

        dao.add(new Word("11","intense","/ɪnˈtens/","adj. 强烈的；紧张的；非常的；热情的","They are having an intense quarrel over a critical issue. \n他们正在为一个关键的问题发生强烈的争执。","[串记] tense adj.紧张的；拉紧的\ntension n.紧张；拉力，张力\nintense adj.紧张的；剧烈的\nintention n.意图；打算\nintent n.目的，意图 adj.急切的，专心的，坚决的","0"));
        dao.add(new Word("12","involve","/ɪn'vɒlv/","vt. 包含；牵涉；使陷于；潜心于","All parts of the machine are involved with each other.\n机器的所有部分都环环相扣。","[联想] in volve，在沃尔沃里面，包含","0"));
        dao.add(new Word("13","despite","/dɪ'spaɪt/","prep. 尽管，不管\nn. 轻视；憎恨；侮辱","Despite the windy day,the reporter still worked outdoors.\n尽管风很大，这个记者仍然在户外工作","[串记] despite=in spite of prep.尽管 n.憎恨\ndespise vt.鄙视，看不起\ndespair n.绝望 vi.绝望，丧失信心\ndesirable adj.令人满意的 n.合意","0"));
        dao.add(new Word("14","species","/'spiːʃiːz; -ʃɪz; 'spiːs-/","n. [生物] 物种；种类\nadj. 物种上的","There are tens of thousands of different species of birds.\n（全球）有成千上万种各不相同的鸟。","[联想] 死是必须的，所有物种都将要灭亡","0"));
        dao.add(new Word("15","optional","/'ɒpʃ(ə)n(ə)l/","adj. 可选择的，随意的\nn. 选修科目","The optional subjects are usually more interesting than majors.\n选修课通常比必修课更有意思。","[词根] option（选择）+al（形容词后缀）=optional（可选择的）","0"));
        dao.add(new Word("16","automatic","/ɔːtə'mætɪk/","adj. 自动的；无意识的；必然的\nn. 自动机械；自动手枪","This is an automatic press that performs shaping operations, such as bumping, heading and pocketing.\n这是一台进行造型操作，如碰撞、装头和压袋的自动压力机。","[串记] automated adj.自动化的；机械化的\nautomatically adv.自动地；机械地；无意识地\nautomation n.自动化；自动操作","0"));
        dao.add(new Word("17","intend","/ɪn'tend/","vt. 打算；想要；意指\nvi. 有打算","Hi,cat,what do you intended to do-eat me,or just watch me?.\n嗨，小猫，你想干嘛？吃掉我还是只是看看我。","[串记] tend v.趋向，倾向；照料\nintend v.打算\nintent n.意图\nextend v.延伸\nextent n.广度\nattend v.参加\npretend v.假装","0"));
        dao.add(new Word("18","conduct","/'kɒndʌkt/","vi. 导电；带领\nvt. 管理；引导；表现\nn. 进行；行为；实施","The man conducts the orchestra at the concert.\n这个人在演奏会上指挥着整个乐队。","[联想] con共同 duck(t)鸭子 一群鸭子需要有带领者，指挥引道","0"));
        dao.add(new Word("19","liar","/'laɪə/","n. 说谎的人","He said to the boy, \"That politician's a liar! Don't believe him!\n那个政客是个骗子！别相信他！","[串记] lie v.躺，位于，说谎 n.谎话，假象\nliar n.说谎者","0"));
        dao.add(new Word("20","illegal","/ɪ'liːg(ə)l/","adj. [法] 非法的；违法的；违反规则的\nn. 非法移民，非法劳工","Occupying a bus lane is illegal.\n占用公交车道是违法行为！。","[串记] legislate v.立法，制定法律\nlegislation n.法律，法规，立法，法律的制定（或通过）\nlegal adj.合法的\nillegal adj.非法的\nlegality n.合法，合法性\nillegality n.非法","0"));

        dao.add(new Word("21","ending","/'endɪŋ/","n. 结局；结尾","We loved the movie, but we all cried at its sad ending.\n我们喜欢这部电影，但它悲惨的结局让我们都哭了。","[串记] at the end of the day 最终，到头来\nby the end of 到……末为止、在……结束时\nbefore the end of 在……结束之前\nin the end 终于，最后","0"));
        dao.add(new Word("22","individual","/ˌɪndɪˈvɪdʒʊəl/","adj. 个人的；个别的；独特的\nn. 个人，个体","The individual toilet cubicle ensures the privacy.\n厕所的独立隔间保障了个人隐私。","[对比] individual：与集体的相对，指个别或个体的\npersonal：指属于或关于某人或某些特定的人，以区别与其他人\nprivate：指属于私人所有或具有私营性质，以区别于集体或公共的，有时含不公开的意味","0"));
        dao.add(new Word("23","register","/'redʒɪstə/","登记；注册；记录；挂号邮寄；把…挂号；正式提出\nn. 登记；注册；记录；寄存器；登记簿","You should register on this page first,then you can use this APP.\n你先注册了这个应用，然后你就可以使用了。","[串记] region n.地区\nregister v.注册\n到了某一个region就要进行register，暂住证","0"));
        dao.add(new Word("24","economical","/iːkə'nɒmɪk(ə)l; ek-/","adj. 经济的；节约的；合算的","This small car is very economical on gasoline.\n这种小型车辆非常节省汽油。","[对比] 共同释义：经济的，财务的\neconomic：除指经济的外，还表示经济上有收益的，有利可图的\neconomical：指节约的，精打细算的\nfinancial：指财政的，财务的，财力的\neconomy：作形容词用在名词前面，构成名词短语，其含义相当于economical","0"));
        dao.add(new Word("25","hint","/hɪnt/","n. 暗示；线索\nvt. 暗示；示意\nvi. 示意","Give me a hint to help me answer this question.\n给我些提示来帮我回答这个问题吧。","[串记] hunt n./v.打猎，搜寻\nhint n.暗示，示意，建议\nhit v.打击，拍打\n根据线索hint找到猎物，打击hit猎物，完成打猎hunt。","0"));
        dao.add(new Word("26","award","/ə'wɔːd/","vt. 授予；判定\nn. 奖品；判决","I can't believe I won the award for best actress.\n真不敢相信我得了最佳女演员奖。","[串记] ward n.病房 v.守护，收容\nreward n.报酬，报答 v.酬谢\naward n.奖赏 v.判定\naware v.意识到","0"));
        dao.add(new Word("27","ensure","/ɪn'ʃɔː; -'ʃʊə; en-/","vt. 保证，确保；使安全","The swimming laps could ensure the safety of the pigs.\n这些游泳圈可以保证小猪们的安全。","[对比] ensure/insure/assure均有“保证”之意。\nensure:侧重使人相信某个行为或力量产生的结果。\ninsure：指保险公司对财产、货物或人生安全的保险。\nassure：侧重消除某人思想上的怀疑或担心，从而有达到目的的保证感。","0"));
        dao.add(new Word("28","alter","/'ɔːltə; 'ɒl-/","vt. 改变，更改\nvi. 改变；修改\nn. (Alter)人名","The landscape has been altered so much in recent years. \n这些年，地貌变化如此之大。","[串记] alter\n[联想] alter v.改变，更改\nalternate n.交替，轮流，间隔\nalternative adj.两者择一的\n音像奥特（曼）、奥特曼会变身，所以是“变”的意思。","0"));
        dao.add(new Word("29","remark","/rɪ'mɑːk/","n. 注意；言辞\nvt. 评论；觉察\nvi. 谈论","The emperor's remark shows he is aware of the arrangement.\n皇帝的评语表明他知道今晚的安排了。","[对比] remark:指通过评论希望引起人们对某事的注意\ncomment：指用揭露或补充细节等的办法来阐明或评论","0"));
        dao.add(new Word("30","overall","/'əʊvərɔːl/","adj. 全部的；全体的；一切在内的\nadv. 全部地；总的说来\nn. 工装裤；罩衫","A merit student should establish overall development.\n学霸就应该全面发展。","[串记] overall adj.全面的，全部的，整体的；总的来说，从头到尾的\novercoat n.大衣，外套\noverseas adj.国外的，海外的，外国的\n[联想] over从头到尾，all所有的，overall全面的","0"));

        dao.add(new Word("31","dim","/dɪm/","adj. 暗淡的，昏暗的；模糊的，看不清的；悲观的，怀疑的\nvt. 使暗淡，使失去光泽；使变模糊\nvi. 变模糊，变暗淡\nn. 笨蛋，傻子","The light is very dim; I can't see who it is.\n灯光非常昏暗，我看不清那是谁。","[对比] ambiguous/dim均有“不确定的，模糊的”之意。\nambiguous：指文章或讲话中，意思可能有多种理解，令人捉摸不透。\ndim：侧重或因光线暗淡，或因年代久远等因素而产生视觉方面的困难。","0"));
        dao.add(new Word("32","brand","/brænd/","vt. 铭刻于，铭记；打烙印于；印…商标于\nn. 商标，牌子；烙印","These companies all have very well-known brands.\n这些公司都有非常知名的品牌。","[对比] brand和trademark均含“商标”之意\nbrand：指生产厂家为自己的产品所取的专用名称\ntrademark：指通过合法注册而印在商品上的特殊标记，即“商标”\n比如“NIKE”耐克就是brand，商标就是trademark，而logo是商标的图案，比如NIKE的logo是一个对勾","0"));
        dao.add(new Word("33","influence","/'ɪnflʊəns/","n. 影响；势力；感化；有影响的人或事\nvt. 影响；改变","Quit smoking! You're negatively influencing your kid!\n戒烟吧！你给你孩子树立了坏榜样！","[串记] flu n.流感\ninfluence n./v.影响，感化（向脑子里流的是什么？思想。思想会影响一个人）\ninfluential adj.有影响力的 n.有势力的人\nimpact n.影响力 v.冲击，撞击，对...产生影响","0"));
        dao.add(new Word("34","appropriate","/əˈprəʊprɪət;(for v.)əˈprəʊprɪeɪt/","adj. 适当的；恰当的；合适的\nvt. 占用，拨出","Cinderalla's foot size is appropriate to the glass shoe.\n灰姑娘刚好能穿进水晶鞋。","[串记] appropriate adj.适当的\napproximate adj.近似的，约略的 v.接近，近似\nappreciate vi. 增值 vt. 赏识， 为…表示感激，领会，使增值","0"));
        dao.add(new Word("35","strategy","/ˈstrætədʒɪ/","n. 战略，策略","I like strategy games that require deep thinking, like chess.\n我喜欢需要深思熟虑的策略性游戏，比如国际象棋。","[串记] strategic adj.关键的，战略上的\nstratigraphy n.地质层\ntactic n.（达到目的）手段，战术，策略\ntactical adj.手段的，战术的","0"));
        dao.add(new Word("36","adequate","/'ædɪkwət/","adj. 充足的；适当的；胜任的","I've prepared adequate snacks for the outing.\n我为这次郊游准备了充足的零食。","[串记] adequate adj.充足的，尚可的，可以胜任的\nadequacy n. 足够; 适当; 妥善性\ninadequate adj.不充分的，不足够的，不适当的\nenough adj.足够的 adv.足够地 n. 很多，充足 ","0"));
        dao.add(new Word("37","distribute","/dɪ'strɪbjuːt; 'dɪstrɪbjuːt/","vt. 分配；散布；分开；把…分类","Santa Claus distributes the gifts to the kids on Christmas Eve.\n圣诞老人在平安夜的时候给小朋友分发礼物。","[串记] allocate v.分配，配给\nadvocate n.提倡者，律师 vt.提倡, 为…辩护，拥护\ndispense v.分配，免除，执行\ndivide v.分开，划分，分配","0"));
        dao.add(new Word("38","efficient","/ɪ'fɪʃ(ə)nt/","adj. 有效率的；有能力的；生效的","The mother is very efficient; she can watch her kids and do her work at the same time.\n这位母亲效率非常高，她可以一边照看孩子一边做自己的工作。","[对比] effective/efficient区别：\neffective：侧重产生实际的效果、效力或具有取得预期效果的能力，指人指物都适用。\nefficient：侧重指积极有效，效率高，效果好，节省精力。指人时强调其能干、熟练的技巧。”。","0"));
        dao.add(new Word("39","emit","/ɪ'mɪt/","vt. 发出，放射；发行；发表","Light bulbs emit light.\n灯泡散发着光线。","[联想] emit倒过来就是time，要逆转时间回到过去，就要把你超光速地发射出去。","0"));
        dao.add(new Word("40","casual","/'kæʒjʊəl; -zj-/","adj. 随便的；非正式的；临时的；偶然的\nn. 便装；临时工人；待命士兵","She wore casual clothing, preferring not to dress up for this event.\n她穿着随意，不太想为聚会盛装打扮。","[串记] casual  n.临时工,便服  adj.临时的\ncasually  adv.随便地，偶然地，临时地\ncasualness  n.偶然，漫不经心，随便\ncause  v.引起、原因","0"));

        dao.add(new Word("41","entitle","/ɪn'taɪt(ə)l; en-/","vt. 称做…；定名为…；给…称号；使…有权利","Only invited wedding guests are entitled to sit here.\n只有被邀请的婚礼宾客才有资格坐在这里。","[串记] title  n.标题，头衔，称号\nentitle  v.使给予，给资格，给...权利，取名为...\nentitlement  n.资格\nsubtitle（下面的标题，下面的字）  n.副标题，字幕\nsubtle（下面有微小的东西）  adj.微妙的","0"));
        dao.add(new Word("42","staff","/stɑːf/","n. 职员；参谋；棒；支撑\nadj. 职员的；行政工作的\nvt. 供给人员；给…配备职员\nvi. 雇用工作人员\nn. (Staff)人名；(德、匈)施塔夫；(瑞典、英)斯塔夫","You can ask any of our staff for help.\n你可以向我们的任何职员请求帮助。","[串记] stuff  n.材料  v.把…装满，塞进\nstiff  adj.僵直的，硬的，苦难的\nstuffy  adj.乏味的,闷热的,古板的\nscoff  n.愚弄  v.讥笑，嘲笑","0"));
        dao.add(new Word("43","link","/lɪŋk/","n. [计] 链环，环节；联系，关系\nvt. 连接，连结；联合，结合\nvi. 连接起来；联系在一起；将人或物连接或联系起来","Social networking sites help link you with your friends.\n社交网络帮助你连接朋友。","[对比] connect:指两事物在一点上相连接，但彼此又保持独立。\nlink：指连环式连接或者其他方式连接。","0"));
        dao.add(new Word("44","appeal","/ə'piːl/","vi. 呼吁，恳求；上诉；诉诸，求助；有吸引力，迎合爱好；（体育比赛中）诉诸裁判\nn. 呼吁，请求；吸引力，感染力；上诉；诉诸裁判\nvt. 将…上诉，对…上诉","She appeals to us to promote gender equality at the conference.\n她在大会上呼吁我们促进性别平等。","[串记] appear  v.出现,似乎\nreal  n. 实在的东西  adj. 真实的,真的  adv. 真正地\nappeal  v.呼吁，恳求，上诉，申诉\nappease  v.平息，抚慰，姑息\nappal  v.使惊骇，惊诧，胆战心惊","0"));
        dao.add(new Word("45","tackle","/'tæk(ə)l/","n. 滑车；装备；用具；扭倒\nvt. 处理；抓住；固定；与…交涉\nvi. 扭倒；拦截抢球","The repairman is able to tackle any problems with his tools. \n该修理工能用他的工具应付任何问题。","[串记] tackle  n.阻截  v.对付，处理\nhandle  n.柄，把手  v.处理，解决，操纵\ndeal with  处理\ncope with  处理","0"));
        dao.add(new Word("46","reputation","/repjʊ'teɪʃ(ə)n/","n. 名声，名誉；声望","He has a good reputation among sportsmen, since he always wins.\n因为经常赢得比赛，所以他在体育圈里有很高的声誉。","[对比] frame/honour/reputation区别：\nframe：普通用词，含义广，一般指好名声，可大可小。\nhonour：侧重因高尚的举止，忠心或诚实而受到公众钦佩和崇敬，得到好名声和荣誉。\nreputation：通常指熟悉某人或某地的人对该人、该地的看法，可好可坏。","0"));
        dao.add(new Word("47","slip","/slɪp/","v.滑到，跌倒，溜走 \nn. 疏漏，差错","The floor is wet--make sure you don't slip and fall.\n地板很湿，请注意不要滑倒。","[串记] slope  n.山坡，斜坡，倾斜  v.倾斜\nsplit  n.裂缝  vi. 裂开  adj. 分裂的\nslap  v.掌击，拍打，掴，拍\nslip  v.滑到  n. 疏漏，差错\nsnap  v.使喀嚓一声折断  n.吧嗒声，快照 adj.仓卒的","0"));
        dao.add(new Word("48","contact","/'kɒntækt/","n. 接触，联系\nvt. 使接触，联系\nvi. 使接触，联系","They try to contact each other by phone,but they fail.\n他们试着打电话给对方，但是联系不上。(先搞懂电话怎么拿吧）","[对比] connect/contact/chain/link均有“连接”之意。\nconnect：指两个事物的连接，以及由一件事联想到另一件事。\ncontact：多指用书信，交流联系交流。\nchain：指事物之间存在的联系，有约束关系。\nlink:多指两件事的联系以及连接。","0"));
        dao.add(new Word("49","assignment","/ə'saɪnm(ə)nt/","n. 分配；任务；作业；功课","My teacher gave me a lot of homework assignments for the weekend.\n我的老师在周末的时候给了我很多家庭作业和课外任务。","[串记] assign  v.指派,分派,分配\nassignable  adj.可分配的，可过渡的\nassignation  n.分配,约会\nassignee  n.受托人，代理人\nassigner  n.分配人，指定人","0"));
        dao.add(new Word("50","legal","/'liːg(ə)l/","adj. 法律的；合法的；法定的；依照法律的\nn. (Legal)人名；(法)勒加尔","Homosexual marriage is legal in certain countries.\n同性恋婚姻在一些国家是合法的。","[串记] legal  adj.法律的，合法的\nlegally  adv.法律上，合法地\nlegality  n.合法性，墨守法规，法律上的义务\nlegalize  vt.使合法化，使得到法律认可\nlogic  n.逻辑，推理，逻辑性","0"));

        dao.add(new Word("51","consume","/kən'sjuːm/","vt. 消耗，消费；使…着迷；挥霍\nvi. 耗尽，毁灭；耗尽生命","This girl consumes a lot of fruit.\n小妹妹吃了很多水果。","[串记] consume  vt. 消耗，吃光，毁灭\nconsumer  n.消费者，用户\ncustomer  n.顾客，主顾\nconsumable  adj.可消费的，会用尽的  n.消费品\npresume  v.推测，假定\nresume  v.重新开始, 又继续  n. 简历","0"));
        dao.add(new Word("52","overlook","/əʊvə'lʊk/","vt. 忽略；俯瞰；远眺；检查；高耸于…之上\nn. 忽视；眺望","It is easy to overlook Mr.Bao in this picture.\n在这张照片中很容易忽视包大人。","[串记] overlook  v.忽视；眺望；俯视\noverlook sb for sth 在某件事上故意忽略某人\noversight  n.勘漏，疏忽；监督\noversee  v.监督，俯瞰；偷看到，无意中看到","0"));
        dao.add(new Word("53","deceive","/dɪ'siːv/","v. 欺骗；行骗","He deceived the old man about the contract he was signing.\n在签合同这件事情上，他欺骗了老人。","[串记] deceit  n.欺骗，欺诈\nfraud  n.欺诈，诈骗；骗子\nconceive  v.想到，设想；怀孕\nreceive  vt.收到；得到；接待\nperceive  v.意识到，察觉，发觉，认为","0"));
        dao.add(new Word("54","assist","/ə'sɪst/","n. 帮助；助攻\nvi. 参加；出席\nvt. 帮助；促进","The nurse will assist you in walking to your car.\n护士会搀扶你走向你的车。","[串记] consist  v.由…组成，存在\npersist  v.坚持，固执；继续存留\nresist  v. 抵抗，抵制\n[联想] 一个（a）姐姐（sister）能帮忙！","0"));
        dao.add(new Word("55","exhaust","/ɪg'zɔːst; eg-/","vt. 排出；耗尽；使精疲力尽；彻底探讨\nvi. 排气\nn. 排气；废气；排气装置","Going after the sun exhausted Kuafu.\n夸父逐日逐得精疲力尽。","[串记] exhaust  v.使筋疲力尽，抽完　n.排气装置；废气\nexhaustible  adj.可空竭的，可耗\nexhaustible resource 不可再生资源\ninexhaustible  adj.无穷无尽的，用不完的","0"));
        dao.add(new Word("56","criticize","/'krɪtɪsaɪz/","vt. 批评；评论；非难\nvi. 批评；评论；苛求","The man often criticized his wife for spending too much money.\n这个男人常常批评他老婆花太多钱。","[串记] critic  n.评论家，批判者，挑剔的人\ncriticism  n.批评；批判；评论\ncriticize  v.批评；评论；责难\ncritical  adj.批评的，文艺评论的，极度重要的，危险的","0"));
        dao.add(new Word("57","characteristic","/kærəktə'rɪstɪk/","adj. 典型的；特有的；表示特性的\nn. 特征；特性；特色","A song-and-dance duet is the characteristic of northeast district.\n二人转是我国大东北地区的特色。","[串记] character  n. 性格；角色；字符，字体\ncharacterize  v.表示...的特性；描述...特性","0"));
        dao.add(new Word("58","discipline","/'dɪsɪplɪn/","n. 学科；纪律；训练；惩罚\nvt. 训练，训导；惩戒","The discipline of the Red Army is very strict. \n红军的纪律十分严格。","[对比]  drill/exercise/discipline均有“练习、训练、锻炼”之意。\ndrill：侧重进行有系统的，严格和重复的练习。\nexercise：指为强壮体魄而进行得锻炼，也可指进行练习以保持已获得的技能。\ndiscipline：既可指训练又可指达到某种熟练程度而进行约束。","0"));
        dao.add(new Word("59","illustrate","/'ɪləstreɪt/","vt. 阐明，举例说明；图解\nvi. 举例","Our manager illustrated the sales with colorful charts. \n我们经理用一些彩色图标解释了我们的销售量。","[串记] illustrative  adj.用作说明的，解说性的  adv.用作说明地，解说性地\nillustrator  n.插图画家\nillustrate  vt. 阐明，举例说明；图解  vi. 举例\nillustration  n.插图，举例，例证","0"));
        dao.add(new Word("60","imitate","/'ɪmɪteɪt/","vt. 模仿，仿效；仿造，仿制","The little girl imitates her mother when she exercises.\n小女孩儿在她妈妈运动的时候模仿她。","[联想] im it我是它 模仿。\n谐音“一枚忐忑”，因为学生模仿了家长的签名，所以是一枚忐忑的心。","0"));

        dao.add(new Word("61","convey","/kən'veɪ/","vt. 传达；运输；让与","The conveyor belt conveys boxes from place to place.\n传送带把箱子运送到不同的地方。","[对比] bring/carry/convey均有“带，拿。取”之意。\nbring：指从某次把人或物带到或拿到说话者所在的地点，强调方向，不着重方式。\ncarry：指把物品从一个地方带到另一个地方，不涉及方向，只强调方法。\nconvey：指通过中间人传递信息，或以某种方式把人或物送到目的地。","0"));
        dao.add(new Word("62","squeeze","/skwiːz/","vt. 挤；紧握；勒索\nvi. 压榨\nn. 压榨；紧握；拥挤；佣金","She squeezes the toothpaste onto the toothbrush.\n她把牙膏挤到牙刷上。","[对比] press/squeeze/compress区别：\npress：普通用词，指一个物体在另一个物体上加压力。\nsqueeze：多指从两面或多面施加压力来压紧、压碎或压出水来。\ncompress：指把某些东西压在一起或使占有较小空间。","0"));
        dao.add(new Word("63","dissolve","/dɪ'zɒlv/","vt. 使溶解；使分解；使液化\nvi. 溶解；解散；消失\nn. 叠化画面；画面的溶暗","This tablet dissolves in water.\n这片药在水中溶解。","[联想] dis（否定：不）solve（解决）\n政府不解决矛盾问题，就等着“解散”或问题“失控”吧。","0"));
        dao.add(new Word("64","chase","/tʃeɪs/","vt. 追逐；追捕；试图赢得；雕镂\nvi. 追逐；追赶；奔跑\nn. 追逐；追赶；追击\nn. (Chase)人名；(英)蔡斯；(法)沙斯","The children are outside chasing bugs.\n孩子们在外面追赶飞虫。","[对比] purse：指坚持不懈、毫不动摇地紧跟、追赶某人某物。\nfollow：多指跟随起引导作用的人或物，跟随的动机可以是善意的，也可以是恶意的。\nchase：指快速追赶或决心追踪，褒义贬义均可用。","0"));
        dao.add(new Word("65","abandon","/ə'bænd(ə)n/","n. 放任；狂热\nvt. 遗弃；放弃","She reluctantly abandons her baby.\n她极不情愿地抛弃了她的孩子。","[对比] abandon/desert/give up区别：\nabandon：强调永远或完全抛弃人或事，这可能是被迫的，也可能是自愿的。\ndesert：着重指违背法律责任和义务，或自己的信仰与誓言的行为，多含非难的意味。\ngive up:侧重指没哟希望或因外界压力而放弃。","0"));
        dao.add(new Word("66","drift","/drɪft/","n. 漂流，漂移；趋势；漂流物\nvi. 漂流，漂移；漂泊\nvt. 使…漂流；使…受风吹积","Our boat drifted away; I had to stay with my female friend on the island.\n我们的船飘走了，我只好和女性朋友在岛上过夜。","[串记] get/catch one's drift 抓住主旨\na snow drift 雪堆\ndrift off 秘密呼呼，入睡\ndrift along 随波逐流，混日子","0"));
        dao.add(new Word("67","launch","/lɔːntʃ/","vt. 发射（导弹、火箭等）；发起，发动；使…下水\nvi. 开始；下水；起飞\nn. 发射；发行，投放市场；下水；汽艇","The space shuttle launched into the sky in a cloud of smoke.\n航天飞机在一片烟雾里被发射到天空中。","[串记] launch oneself into 投入\nlaunch with 开始\nbegin with 开始\nstart with 开始","0"));
        dao.add(new Word("68","flexible","/'fleksɪb(ə)l/","adj. 灵活的；柔韧的；易弯曲的","She's so flexible because she's practiced yoga for so long.\n练了很久的瑜伽，让她的身体很柔软。","[串记] flex  v.弯曲  n.屈曲  adj.弹性工作制的\nflexile  adj.柔韧的; 灵活的\nflexibility  n. 灵活性\nflexion  n.（关节、肢的）弯曲","0"));
        dao.add(new Word("69","rare","/reə/","adj. 稀有的；稀薄的；半熟的\nadj. 杰出的；极度的；非常好的\nadv. 非常；极其\nvi. 用后腿站起；渴望","Pandas are hard to find because they're so rare.\n熊猫很难被找到，因为它们太稀有了。","[串记] rare  adj.稀有的\nbare  adj.裸露的\nmere  adj.仅仅的\n[联想] 稀有的 rare要care 保护。","0"));
        dao.add(new Word("70","parallel","/'pærəlel/","n. 平行线；对比\nvt. 使…与…平行\nadj. 平行的；类似的，相同的","These tracks run parallel to each other.\n这些铁轨相互平行。","[对比] parallel/alike/comparable/similar均有“相似”之意。\nsimilar和alike指整体或某部分相似，用法一样，可互换。\ncomparable：指可以放在一起相似的物或人。\nparallel：则用在实际上或表面上相似得事物或用于表示其在发展、结构、历史等方面极其相似。”","0"));

        dao.add(new Word("71","guidance","/'gaɪd(ə)ns/","n. 指导，引导；领导","My trainer gave me some guidance about my exercise schedule.\n我的教练给了我一些关于我训练课程的指导。","[串记] garden  n.花园\nguide  n.导游  v.给…导游\nguidance  n.引导，指导\nguideline  n.指导路线，准则","0"));
        dao.add(new Word("72","withstand","/wɪð'stænd/","vt. 抵挡；禁得起；反抗\nvi. 反抗","I can't withstand any more strong sun!\n我不能忍受这强烈的阳光！","[串记] withdraw  v.撤退，收回，提款\nwithdrawal  n.撤退；收回；提款；取消；退股\nwithhold  v.拒绝给某事物，抑制\nwithstand  v.忍受；抵挡","0"));
        dao.add(new Word("73","response","/rɪ'spɒns/","n. 响应；反应；回答","My teacher was impressed with my response to the question.\n我对这个问题的回答，给我的老师留下了深刻的印象。","[串记] respond  v.回答，做出反应\nresponse  n. 响应；反应；回答\nresponsible  adj. 有责任的\nresponsibility  n. 责任，负担","0"));
        dao.add(new Word("74","kit","/kɪt/","n. 工具箱；成套工具\nvt. 装备\nvi. 装备\nn. (Kit)人名；","Here’s the most basic computer maintenance kit that I think any user should have. \n这些是最基本的电脑维护工具包，我觉得任何用户都应该有。","[串记] kite  n.风筝\nkick  n.踢  v.踢\nknot  n.绳结，结合，树的节  v.打结\nknit  v.编结，针织","0"));
        dao.add(new Word("75","pitch","/pɪtʃ/","vi. 倾斜；投掷；搭帐篷；坠落\nvt. 投；掷；定位于；用沥青涂；扎营；向前倾跌\nn. 沥青；音高；程度；树脂；倾斜；投掷；球场","It's my dog's turn to pitch and my turn to fetch.\n这次轮到狗狗来投球，我来捡球了。","[对比] cast/throw/pitch区别：\ncast：常可与throw互换，指迅速扔出一个重量较轻的物体。\nthrow：普通用词，使用广泛，仅指用力抛掷，不涉及动作方式或感情色彩。\npitch：指随意地、轻轻地投或扔，侧重方向性和有明确的目标。","0"));
        dao.add(new Word("76","file","/faɪl/","n. 文件；档案；文件夹；锉刀\nvt. 提出；锉；琢磨；把…归档\nvi. 列队行进；用锉刀锉","The records had been all balled up by inefficient file clerks.\n因不称职的档案(或卷宗)管理员，档案全被弄得一团糟。","[串记] pile  n.一堆  v.堆积，累积\ntile  v.贴砖于，用瓦盖  n.瓦\nfile  n.文件，档案\nmile  n.英里\nsile  v.留下","0"));
        dao.add(new Word("77","collect","/kə'lekt/","vt. 收集；募捐\nvi. 收集；聚集；募捐\nadv. 由收件人付款地\nadj. 由收件人付款的","I collect old stamps for fun.\n我因为好玩而收藏旧邮票。","[串记] collect  v.收集；领取；募捐\ncollege  n.学院，高等专科学校；大学\nwallet  n.皮夹，钱包","0"));
        dao.add(new Word("78","crack","/kræk/","vt. 使破裂；打开；变声\nvi. 破裂；爆裂\nn. 裂缝；声变；噼啪声\nadj. 最好的；高明的","I cracked my phone by hitting the nut;I miss my Nikia. \n我砸核桃把手机砸裂了真怀念我（我以前）的诺基亚。","[对比] crack/burst均有“打破，弄碎”之意。\ncrack：多指因长期使用或经受压力，物体呈现裂纹、裂口，但一般没成碎片\nburst：指某物因内部外部压力过大而出现严重破裂、爆开。","0"));
        dao.add(new Word("79","negotiation","/nɪgəʊʃɪ'eɪʃ(ə)n/","n. 谈判；转让；顺利的通过","The negotiation went well and they finally reached an agreement. \n谈判进行得很顺利，最后他们达成了协议。","[串记] negotiate  v.谈判，交涉\nnegotiable  adj.可通过谈判解决的；可协商的\nnegotiation  n.谈判；转让\nnegotiant  n.谈判者；磋商者","0"));
        dao.add(new Word("80","switch","/swɪtʃ/","vt. 转换；用鞭子等抽打\nvi. 转换；抽打；换防\nn. 开关；转换；鞭子","Diddle the switch see if the light comes on.\n上下快速拨动电灯开关看看是否来电了。","[串记] switch attention to  转移注意力\ndraw attention to  吸引注意力\npay attention to  注意力集中\nswitch off 关\nswitch on 开","0"));

        dao.add(new Word("81","acquire","/ə'kwaɪə/","vt. 获得；取得；学到；捕获","Freedom is something we all want, but many of us are not sure how to acquire it, or even what we mean by it.\n或者你有财务上的困扰吗？ 自由是我们都想得到的，但我们当中很多人都不确信如何才能获得，甚至不知道它意味着什么。","[联想] 有了require（要求），就要inquire（询问），然后acquire（获得）。","0"));
        dao.add(new Word("82","boast","/bəʊst/","vt. 夸口说，自吹自擂说；以有…而自豪\nn. 自夸；值得夸耀的事物，引以为荣的事物\nvi. 自吹自擂","Well, maybe you are, but you should not boast so much. \n嗯，也许你是，但是你不应该如此吹嘘。","[联想] 在海岸（coast）边自夸（boast）自己的烤肉（roast）技术。","0"));
        dao.add(new Word("83","ideal","/aɪ'dɪəl; aɪ'diːəl/","adj. 理想的；完美的；想象的；不切实际的\nn. 理想；典范","Her ideal weight is about twenty kilos lighter.\n她理想的体重大约轻20kg。","[串记] ideal  n.理想  adj.理想的\nidealism  n.理想主义\ndealing  n.交易，交往\ndealership  n.代理商，代理权\ndealer  n.做买卖的人","0"));
        dao.add(new Word("84","reluctant","/rɪ'lʌkt(ə)nt/","adj. 不情愿的；勉强的；顽抗的","My cat felt reluctant when taking a selfie with me.\n和我自拍的时候，我的喵喵表现得很不情愿。","[串记] unwilling  adj. 不愿意的，不情愿的，勉强的\ndisinclined  adj.不情愿，勉强\nunenthusiantic  adj.不热心的，缺乏热情的\nresistant  adj.抵抗的\nopposed  adj.反对的，敌对的","0"));
        dao.add(new Word("85","drain","/dreɪn/","vi. 排水；流干\nvt. 喝光，耗尽；使流出；排掉水\nn. 排水；下水道，排水管；消耗","The raw sewage drains into the river.\n未经处理的污水排进了河流。","[联想] dry干的 rain雨水\ndry the rain 把雨水变干“排水，流干”。","0"));
        dao.add(new Word("86","chill","/tʃɪl/","n. 寒冷；寒意；寒心\nadj. 寒冷的；冷漠的；扫兴的\nvt. 冷冻，冷藏；使寒心；使感到冷\nvi. 冷藏；变冷","I feel a chill coming on. The temperature is set too low.\n我感觉有点冷。温度调得太低了。","[串记] chill  n.寒气  v.变冷，冷静\ncool  adj.凉爽的\ncold  adj.寒冷的\nfreeze  v.结冰，凝固\nfrozen  adj.冰冻的，极冷的","0"));
        dao.add(new Word("87","expectation","/ekspek'teɪʃ(ə)n/","n. 期待；预期；指望","The hungry boy waited in expectation for his food.\n这个饥饿的男孩一脸期待地等着他的食物。","[串记] expect  v.期待\nexpectation  n.期待\ninspect  v.坚持\ninspection  n.检查\nprospect  n.前景\nsuspect  v.怀疑","0"));
        dao.add(new Word("88","press","/pres/","vt. 压；按；逼迫；紧抱\nvi. 压；逼；重压\nn. 压；按；新闻；出版社；[印刷] 印刷机","Press the button on the phone to make a call.\n按电话上的按键来打电话。","[联想] press 按 pressure 压力 \n按了才会有压力。","0"));
        dao.add(new Word("89","plus","/plʌs/","n. 正号，加号；好处；附加额\nadj. 正的；附加的\nprep. 加，加上","One plus one equals two... Hopefully you knew that.\n1+1=2，希望你能懂这个。","[串记] plus=add 加+\nminus=subtract 减-\nmultiply=times 乘×\ndivide（into）除÷","0"));
        dao.add(new Word("90","isolate","/'aɪsəleɪt/","vt. 使隔离；使孤立；使绝缘\nn. [生物] 隔离种群\nadj. 隔离的；孤立的vi. 隔离；孤立\n","The island is isolated from the rest of the world; very few visitors come here.\n这座岛与世隔绝，人迹罕至。","[联想] i+so+late 我来的这么晚，所以我被“孤立，隔离”了。\ninsulate 把人“隔离”起来，简直就是一种侮辱（insult）。\nseparate  adj. 各别的，不相连的  v. 分开，分离","0"));

        dao.add(new Word("91","abundant","/əˈbʌndənt/","adj. 丰富的；充裕的；盛产","Holland has an abundant supply of tulips.\n荷兰有丰富的郁金香供应源。","[串记]  abundant  adj. 丰富的\nabundance  n.丰富\nredundant  adj.多余的，过剩的\n词组：be abundant in 富于...","0"));
        dao.add(new Word("92","forbid","/fə'bɪd]/","vt. 禁止；不准；不允许；〈正式〉严禁","We forbid smoking in the restaurant.\n餐厅禁止吸烟。","[对比]  ban/forbid/prohibit区别：\nban：指合法地或由于社会压力而禁止，含谴责或不赞同的态度，ban...from sth./doing sth。\nforbid：比prohibit通俗，用于较小事物，或个人、上级、官方、长辈做出的禁止命令和规定，或客观条件不允许，forbid sb to do sth。\nprohibit：指通过法律、法令、警告等做出禁止命令的正式规定。","0"));
        dao.add(new Word("93","solve","/sɒlv/","vt. 解决；解答；溶解\nvi. 作解答","I will solve this math problem in a minute.\n我马上就能解出这道数学题。","[串记]  solve  v.解决\nsolution  n.解决办法，溶液\nresolve  v.解决，决心要\nresolute  adj.坚决的\nresolution  n.决心\nabsolve  v.赦免","0"));
        dao.add(new Word("94","indicate","/'ɪndɪkeɪt/","vt. 表明；指出；预示；象征","The compass indicates that north is that way.\n指南针指示的那边才是北。","[串记]  dictator（发布命令的人） n.独裁者\npredict（前沿的命令） v.预言\nindicate（往里面偷偷发布命令） v.暗示\ndictation（听老师发令） n.听写","0"));
        dao.add(new Word("95","contrast","/'kɒntrɑːst/","vi. 对比；形成对照\nvt. 使对比；使与…对照\nn. 对比；差别；对照物","In chess, the contrast between black and white is easy to see.\n在国际象棋里，黑白两棋的差异显而易见。","[对比] contrast/compare均有“对比”之意。\ncontrast：多指明显不同的事物相对比\ncompare：多指类似的事物相比较。","0"));
        dao.add(new Word("96","insult","/ɪn'sʌlt/","vt. 侮辱；辱骂；损害\nn. 侮辱；凌辱；无礼","It doesn't help to insult other drivers.\n辱骂其他的司机也无济于事。","[串记]  abuse  n.滥用  vt.滥用, 虐待\nmistreat  vt.虐待\ninjure  v.伤害，损害，损伤\ntorture  n.酷刑，折磨  v.对…施以苦刑\nbully  n.恃强欺弱者  v.威吓，欺负\ninsult  v.侮辱，凌辱  n.侮辱的言词或行为","0"));
        dao.add(new Word("97","skim","/skɪm/","vt. 略读；撇去…的浮物；从…表面飞掠而过；去除；（为逃税而）隐瞒（部分收入）\nvi. 浏览；掠过\nn. 撇；撇去的东西；表层物；瞒报所得的收入\nadj. 脱脂的；撇去浮沫的；表层的","The sea bird skims the water's surface for a fish.\n海鸟在捕鱼时轻轻掠过水面。","[串记] ski  n.滑雪板  v.滑雪\nskin  n.皮肤，外皮  v.剥皮，去皮\nskim  v.浏览，略读\nskip  v.蹦跳，遗漏  n.蹦跳","0"));
        dao.add(new Word("98","charge","/tʃɑːdʒ/","n. 费用；电荷；掌管；控告；命令；负载\nvt. 使充电；使承担；指责；装载；对…索费；向…冲去\nvi. 充电；控告；索价；向前冲；记在账上","I plug my battery in to charge it.\n我把我的电池放进去充电。","[串记] in charge of 管理，负责\ntake charge of 接管\nin the charge of 被...负责\ncharge with 控告\ncharge at 在充电","0"));
        dao.add(new Word("99","candidate","/'kændɪdeɪt; -dət/","n. 候选人，候补者；应试者","Both candidates told us why we should vote for them. \n两个候选人都告诉我们，为何我们应该选他。","为了获得女神欢心，男友候选人准备了candy 糖果 去date 约会。 ","0"));
        dao.add(new Word("100","chat","/tʃæt/","vi. 聊天；闲谈\nvt. 与…搭讪；与…攀谈\nn. 聊天；闲谈","The women chat casually about their lives.\n女人们随意地闲谈她们的生活。","[串记] chat away 不停得聊天\nchat up 跟...搭讪\nchat about sth 闲聊某事\nchat with 与...闲聊","0"));

        dao.add(new Word("101","spoil","/spɒɪl/","vt. 溺爱；糟蹋；破坏；掠夺\nvi. 掠夺；变坏；腐败\nn. 次品；奖品","The old cheese is beginning to spoil--how disgusting.\n这块过期的奶酪开始变质了，真恶心。","[联想] spoil（谐音：包邮）会spoil（宠坏）我们上瘾网购，都是些spoil（变质）的东西，spoil（毁坏）我们的身体，成为商家的spoil（战利品）。","0"));
        dao.add(new Word("102","guard","/gɑːd/","n. 守卫；警戒；护卫队；防护装置\nvi. 警惕\nvt. 保卫；监视","The guard stood outside and defended the palace gates.\n警卫站在外面看守宫殿的大门。","defend/protect/guard均有“保护，保卫”之意。\ndefend：普通用词，指用武力或其他措施使人或物不受损失，消除危险。\nprotect：指用某种手段作为防御工具以防危险或伤害。\nguard：指保持警惕以防可能的攻击或伤害。","0"));
        dao.add(new Word("103","remote","/rɪ'məʊt/","adj. 遥远的；偏僻的；疏远的\nn. 远程","Have you seen the remote control for the air conditioner?\n你看到空调的遥控器了吗？","[对比] remote/distant/far区别：\ndistant：指时间上、空间上的遥远，也可指亲属关系上的疏远，常用于比喻。\nfar：表示实际距离的远和时间的遥远，常用于文学物体，用来描写异国风光或景色等。\nremote：指时间或距离上是遥远的，也指在感情、兴趣等方面距离很大的，还指关系方面疏远的或淡薄的。","0"));
        dao.add(new Word("104","deliver","/dɪ'lɪvə/","vt. 交付；发表；递送；释放；给予（打击）；给…接生\nvi. 实现；传送；履行；投递\nn. 投球","Please deliver the package to the front door.\n请从前门送快递。","[串记] deliverer  n. 拯救者，交付者，投递者\ndelivery  n. 投递，分娩\ndeliver the goods  交货，履行诺言\ndeliver up  交出，放弃\ndeliver from  从...处释放出来","0"));
        dao.add(new Word("105","violate","/'vaɪəleɪt/","vt. 违反；侵犯，妨碍；亵渎","You violated the law, so you'll have to go to jail.\n你违反了法律，所以必须被送进监狱。","[串记] violate  v.违反，违背，侵犯  \nviolence  n.暴力，激烈\nviolent  adj.猛烈的，暴力的\nviolet  n.紫罗兰，紫罗兰色","0"));
        dao.add(new Word("106","survive","/sə'vaɪv/","vt. 幸存；生还；幸免于；比...活得长\nvi. 幸存；活下来","It's hard for plants to survive in the desert.\n对植物来说，在沙漠里幸存很困难。","[串记] survive  v.活下来，幸存\nsurviving  adj.继续存在的；未死的\nsurvival  n. 生存，残存物  adj. 救生的\nsurvivor  n.生还者，残存物","0"));
        dao.add(new Word("107","enroll","/ɪn'rəʊl/","vt. 登记；使加入；把...记入名册；使入伍\nvi. 参加；登记；注册；记入名册","Every Autumn we have to enroll in classes.\n每年秋天我们都得入学。","[串记] register  v.登记，注册\nenroll  v. 入学，加入，参加\nrecruit  v.招募(新兵)  n.新兵，新成员","0"));
        dao.add(new Word("108","threaten","/'θret(ə)n/","vt. 威胁；恐吓；预示\nvi. 威胁；可能来临","My wife threatened to divorce me if I lied to her again.\n我老婆威胁我说，如果再骗她就离婚。","[串记] threat  n.恐吓，威胁\nthreaten  v.威胁, 恐吓\nmenace  v.威胁，威吓  n.威胁\ntheatre/theater  n.剧场","0"));
        dao.add(new Word("109","suspect","/ˈsʌspekt; (for v.) səˈspekt/","n. 嫌疑犯\nadj. 可疑的；不可信的\nv. 怀疑；猜想","The suspect is believed to have attacked an old lady.\n这个疑犯被怀疑袭击了一个老太太。","[对比] doubt/suspect/distrust区别：\ndoubt：多指因证据不足或者仅凭证据还不能肯定而产生怀疑，多含否定意味。\nsuspect：指猜疑，疑心，肯定意味较多。\ndistrust：指疑惑，猜疑，不信任。\nsuspicious  adj.可疑的; 感到怀疑的\nsuspicion  n.怀疑，疑心，猜疑","0"));
        dao.add(new Word("110","screen","/skriːn/","n. 屏，幕；屏风\nvt. 筛；拍摄；放映；掩蔽\nvi. 拍电影","The movie theater's screen is so large!\n这个电影院的屏幕好大！","[联想] 绿色（green）的屏风（screen）后面有人在尖叫（scream）。\nscreener  n.审查者","0"));

        dao.add(new Word("111","introduction","/,ɪntrə'dʌkʃ(ə)n/","n. 介绍；引进；采用；入门；传入","My introduction went well, but he didn't do such a good job at introducing himself.\n我的自我介绍还不错，呃，可这家伙的自我介绍……","[串记] introduce  v.介绍；传入，引进\nintroduction  n. 介绍；引进\nintroductory  adj.介绍性的\nrecommend  v.推荐，介绍，劝告","0"));
        dao.add(new Word("112","faithful","/'feɪθfʊl; -f(ə)l/","adj. 忠实的，忠诚的；如实的；准确可靠的","Dogs are the most faithful, loyal pets you can have.\n狗是你最忠实的宠物。","[串记] faithless  adj. 不忠实的，无信的，无宗教信仰的\nfaithfully  adv.忠实地，如实地，诚心诚意地\nfaith  n.信任，信心，信仰\nfaithfulness  n.忠诚\nfaithful  adj.忠诚的，如实的","0"));
        dao.add(new Word("113","investigate","/ɪn'vestɪgeɪt/","v. 调查；研究","The detective investigates the ground, hoping to learn something about the case.\n侦探勘察了地面，希望可以找到一些案件的线索。","[串记] investment  n.投资，投资额，投入\ninvestor  n. 投资者\ninvestigative  adj.研究的，调查的，好调查的\ninvestigator  n.研究者，调查者，侦查员\ninvestigate  v.调查，研究","0"));
        dao.add(new Word("114","claim","/kleɪm/","vi. 提出要求\nvt. 要求；声称；需要；认领\nn. 要求；声称；索赔；断言；值得","She claims her baggage at the airport.\n她在机场领取行李。","[串记] claim  v.声称，认领，索赔\nacclaim  n. 欢呼, 赞扬   v.欢呼，喝彩\nexclaim  v.呼叫，惊叫\nproclaim  v.声明，宣告，表明\nreclaim  n. 改造，废物回收利用  vt. 开拓，感化","0"));
        dao.add(new Word("115","burst","/bɜːst/","vi. 爆炸; 迸发; 突然出现; 充满\n vt. 使爆炸; 使胀满; 使绽开\nn. 爆发，突发；爆炸","The balloon got so big that it burst.\n这个气球被撑得太大了，结果爆炸了！","[串记] burst into + n.\nburst into laughter  突然大笑\nburst out + v-ing\nburst out crying  突然大哭","0"));
        dao.add(new Word("116","conference","/'kɒnf(ə)r(ə)ns/","n. 会议；讨论；协商；联盟；（正式）讨论会；[工会、工党用语]（每年的）大会\nvi. 举行或参加（系列）会议","I attend the conference to learn about what other people in my profession are doing.\n我参加这个研讨会去了解同行在做什么。","[串记] reference  n.参考   vt.附…以供参考，引用\ncongress  n.会议，国会，议会\nprogress  n.进步；前进，进展\nconfer  v.协商，授予","0"));
        dao.add(new Word("117","rank","/ræŋk/","n. 排；等级；军衔；队列\nadj. 讨厌的；恶臭的；繁茂的\nvt. 排列；把…分等\nvi. 列为；列队","I don't like the way our teacher ranks all the students from best to worst.\n我不喜欢老师这种把所有学生从最好到最差分等级的做法。","[联想] 开tank（坦克）的人rank（等级）都很高。","0"));
        dao.add(new Word("118","comprehension","/kɒmprɪ'henʃ(ə)n/","n. 理解；包含","The big question mark implies his poor comprehension.\n这个大大的问号表明他理解力不够。","[串记] comprehensive  adj.综合的；理解的   n. 综合学校\ncomprehend  v.了解，领会，由…组成\n全面的（comprehensive）理解（comprehension）","0"));
        dao.add(new Word("119","decrease","/dɪ'kriːs/","n. 减少，减小；减少量\nv. 减少，减小","Our sales have decreased for the last two years, and now we're out of money.\n这两年我们的销售都在减少，现在我们没钱了。","decrease/diminish/dwindle均有“减少”之意。\ndecrease：指逐渐地，不断地减少\ndiminish：侧重大小、数量和重要性的不断减小，强调减小的部分。\ndwindle：指逐渐减小，但强调变得越来越少终致全无。","0"));
        dao.add(new Word("120","favourable","/'feɪv(ə)rəb(ə)l/","adj. 有利的，顺利的；赞成的\nn. 有利","The crowd's reaction to the game was generally favourable: they loved it.\n人们对这场比赛的反应普遍很好，他们很喜欢。","[串记] favor  n.好感，赞同  v.赞同，喜爱\nunfavorable  adj.不顺利的，相反的，令人不愉快的\nbe favourable to  有利的","0"));

        dao.add(new Word("121","exchange","/ɪks'tʃeɪndʒ; eks-/","n. 交换；交流；交易所；兑换\nvt. 交换；交易；兑换\nvi. 交换；交易；兑换","This is a good place for us to exchange ideas.\n这是个不错的地方让我们交换想法。","[串记] exchangeable  adj.可交换的；可兑换的\nexchanger  n.交换器；交易所；交换程序\nexchangeability  n.[贸易]可交换性\nexchange  n. 交换  v.交换，交易","0"));
        dao.add(new Word("122","connection","/kəˈnekʃn/","n. 连接；关系；人脉；连接件","Each one of these wires is an Internet connection.\n这些线缆中的每一条都是一个互联网连接。","[对比] connection/combine/relate/associate均有“连接”之意。\nconnect：指两事物在某一点上相连接，但彼此又保持独立。\ncombine：指两个以上结合在一起。\nrelate：指有亲戚或婚姻关系。\nassociate：指人与人友好和平，平等地联合在一起。","0"));
        dao.add(new Word("123","county","/'kaʊnti/","n. 郡，县","This state is divided into several counties.\n这个国家被分为了若干个郡。","[联想] 用计算器（counter）计算（count）国家（country）的省（province）市（city）县（county）镇（town）村庄（village）的数量（amount）记账（account）。","0"));
        dao.add(new Word("124","confront","/kən'frʌnt/","vt. 面对；遭遇；比较","\"We have to talk!\" shouted the woman as she confronted her boyfriend.\n“我们必须谈谈！”这个女人正视着她男朋友然后吼道。","[串记] confront with  使面临，使面对\nconfront danger  勇敢地面对危险\nconfront challenges  面对挑战\nequal confront 平等对抗","0"));
        dao.add(new Word("125","region","/'riːdʒ(ə)n/","n. 地区；范围；部位","I live in the southwest region of China.\n我住在中国的西南地区。","[对比] district/region/area/section均有“地区”之意。\ndistrict：多指由政府等机构出于行政管理等目的而明确划分的地区。\nregion：常指地球上、大气中具有自热分界线的区域，特指按照气候、人体或其他特征明显、自成一体的地区。\narea：指界限不分明的一部分。\nsection：指城市、国家或天然界线形成的地区。","0"));
        dao.add(new Word("126","vary","/'veərɪ/","vi. 变化；变异；违反\nvt. 改变；使多样化；变奏","These dogs vary in appearance.\n不同品种狗的样子可能会差别非常大。","[串记] vary  v.改变，变化；使多样化\nvariety  n.变化，多样性\nvarious  adj.各种各样的，不同的\nvariable  n.可变物，变量  adj.易变的，可变的\nvariation  n.变异，变化，变奏曲","0"));
        dao.add(new Word("127","commercial","/kə'mɜːʃ(ə)l/","adj. 商业的；营利的；靠广告收入的\nn. 商业广告","Commercial businesses make a lot of money.\n商业公司赚了很多钱。","[串记] commerce  n.商业，贸易\ncommercialized  adj.商业化的  v.使商品化\ncommercially  adv.商业上\ncommercialization  n.商品化，商业化\ncommercialism  n.商业主义，营利主义","0"));
        dao.add(new Word("128","transform","/træns'fɔːm; trɑːns-; -nz-/","vt. 改变，使…变形；转换\nvi. 变换，改变；转化","A convertible car can transform its shape.\n敞篷车能改变自己的外形。","[串记] transfer  v.转移；调任  n. 转让；转移\ntransform  v.改变，转换\ntransaction  n.办理，事务，交易，学报\ntransformation  n.变化，改造，转变","0"));
        dao.add(new Word("129","discharge","/dɪs'tʃɑːdʒ/","vt. 解雇；卸下；放出；免除\nvi. 排放；卸货；流出\nn. 排放；卸货；解雇","The ass-itch boy spoiled the circuit and discharged the electricity. \n熊孩子破环电路把电放了。","[对比] discharge/dismiss/fire均有“解雇，开除”之意。\ndischarge：指有理由的解雇，含几乎不重复用的意味。\ndismiss：语气最轻，一般只有从上文才能看解雇的原因或理由。\nfire：多指被断然地突然解雇，其行动犹如开枪一样干净利落。","0"));
        dao.add(new Word("130","enable","/ɪn'eɪb(ə)l; en-/","vt. 使能够，使成为可能；授予权利或方法","Switching it to \"on\" will enable the fire security system.\n把这个换到“打开”的位置就可以启动火警安全系统。","[串记] able  adj.能够，有能力的\nunable  adj.不能的，不会的\nenable  v.使能够，使可能\ndisable  vt.使无能，使伤残","0"));

        dao.add(new Word("131","absorb","/əb'zɔːb; -'sɔːb/","vt. 吸收；吸引；承受；理解；使…全神贯注","My daughter is absorbed in her story book.\n我女儿被她的故事书吸引住了。","[对比] absorb/suck/digest均有“吸引”之意。\nabsorb：既可指吸收光、热、液体等具体东西，又可指吸引知识等抽象概念的东西。\nsuck：可与absorb换用，但还可以有“吮吸”之意。\ndigest：侧重在消化道内改变事物的化学结构后被人体吸收。","0"));
        dao.add(new Word("132","personnel","/pɜːsə'nel/","n. 人事部门；全体人员\nadj. 人员的；有关人事的","Only company personnel are allowed into this building.\n只有公司职员才可以进入这座大楼。","[串记] cast  n.投掷物，演员表  v.放钓，投，掷\nstaff  n.职员，参谋，棍，（乐）五线谱\ncrew  n.全体船员，乘务员，职员","0"));
        dao.add(new Word("133","competitor","/kəm'petɪtə/","n. 竞争者，对手","You guys are tough competitors, but I bet I 'll win.\n虽然你们是实力很强的对手，但是我敢打赌最后赢的一定是我！","[串记] compete  v.比赛，与...竞争\ncompetition  n.竞争，比赛，竞争者\ncompetitive  adj.竞争的，好胜的\ncompetence  n.能力，胜任，称职\ncompetent  adj.有能力的，能干的，胜任的","0"));
        dao.add(new Word("134","campaign","/kæm'peɪn/","vi. 作战；参加竞选；参加活动\nn. 运动；活动；战役","Many people came to support the president's campaign.\n很多人都来这儿支持总统的竞选活动。","[串记] campaign  n.竞选活动，战役  v.从事活动，参加运动\ncompanion  n.同伴，志同道合的人  vt.陪伴，陪同\ncompetition  n.竞争，比赛，竞争者\nchampion  n.冠军，得胜者  adj.夺得第一名的，优胜的","0"));
        dao.add(new Word("135","crisis","/'kraɪsɪs/","n. 危机；危险期；决定性时刻\nadj. 危机的；用于处理危机的","The employment crisis has affected many families.\n就业危机影响了很多家庭。","[对比] crisis/emergency均有“危急”之意。\ncrisis：含义广泛，可指国家存亡、历史或人的生命、疾病等面临危机关头。也可指好的或恶化的转折点。\nemergency：多指突然发生的出乎意料的紧急情况或事故。","0"));
        dao.add(new Word("136","debate","/dɪ'beɪt/","v. 辩论，争论，讨论\nn. 辩论；辩论会","We had a debate about who was the smartest.\n我们有过一个关于谁最聪明的争论。","[对比] argument/controversy/conflict/debate均有“争执，不和”之意。\nargument：侧重指深刻的意见分歧，多指对非常重要的问题的辩论。\nconflict：指双方坚持己见互不妥协，怀有敌意的争论，多暗示分歧极为重要。\ndebate：通常指经过仔细组织和计划的个人或团体之间的辩论。","0"));
        dao.add(new Word("137","enrich","/ɪn'rɪtʃ; en-/","vt. 使充实；使肥沃；使富足","Smart phones provide entertainments and enrich our life.\n智能手机提供了娱乐节目同时也使我们生活更丰富。","[串记] rich  adj.富有的；肥沃的；昂贵的\nenrich  vt.使充实，使肥沃，使富足","0"));
        dao.add(new Word("138","focus","/'fəʊkəs/","n. 焦点；中心；清晰；焦距\nvt. 使集中；使聚焦\nvi. 集中；聚焦；调节焦距","Make sure your subject is in focus before taking the photo.\n拍照前要确保你的物体对焦。","[串记] concentrate/focus区别：\nconcentrate：指把人或事物集中在一起，也可指把精力或注意力集中与某一事物上。\nfocus：侧重把光、热、射线等集中于某一点，也可把思想或精力集中于某人或者某事情上。","0"));
        dao.add(new Word("139","original","/ə'rɪdʒɪn(ə)l; ɒ-/","n. 原件；原作；原物；原型\nadj. 原始的；最初的；独创的；新颖的","He was a very original thinker, always coming up with new ideas.\n他是个很有原创性的思想者，总是有很多新点子。","[串记] origin  n.起源，由来，出身\noriginal  adj.最初的；新颖的\noriginate  v.起源，开始\noriginator  n.创始人，发明者，起源，起因\noriginally  adv.最初，起初，本来","0"));
        dao.add(new Word("140","worldwide","/'wɜːl(d)waɪd; wɜːl(d)'waɪd/","adj. 全世界的\nadv. 在世界各地","Our parcel service has offices worldwide.\n我们的快递服务在全世界都有办事处。","[串记] worldwide  adj.全世界的\nworld-famous  adj.举世闻名的","0"));

        dao.add(new Word("141","aware","/ə'weə/","adj. 意识到的；知道的；有…方面知识的；懂世故的","The dog is alert and aware.\n这只狗很警觉。","[对比] aware/conscious/sensible均有“意识到的”之意。\naware：强调通过耳闻目染或感觉而得到的信息，也指敏锐的观察和推测，侧重感知，多和of一起用。\nconscious：指内心的感觉，强调深刻的心理活动。\nsensible：侧重通过直觉或理性感觉意识到某物的存在。","0"));
        dao.add(new Word("142","means","/miːnz/","n. 手段；方法；财产\nv. 意思是；打算（mean的第三人称单数） [复数means]","I'll push the nail in by means of this hammer.\n我要用这把锤子钉钉子。","[串记] mean  adj.平均的，下贱的  n.平均值\nmeans  n.方法，手段；工具\nmeaningful  adj.有意义的；意味深长的；重要的\nmeaningless  adj.无意义的\nmeanwhile  adv.同时，其间  n.其间","0"));
        dao.add(new Word("143","indispensable","/ɪndɪ'spensəb(ə)l/","adj. 不可缺少的；绝对必要的；责无旁贷的\nn. 不可缺少之物；必不可少的人","Personality is like underwears that can’t be seen but indispensable.\n人品就像内裤，虽然看不见，但是必须有。","[串记] dispensable  adj.不必要的，可有可无的\ndispensation  n.分配，免除\ndispense  v.分配；免除；执行","0"));
        dao.add(new Word("144","beneficial","/benɪ'fɪʃ(ə)l/","adj. 有益的，有利的；可享利益的","It would be beneficial for you to go outside every once in a while.\n偶尔出去走走对你有好处。","[串记] beneficial  adj.有益的，有利的；可享利益的\nbenefit  n. 好处；利益 v.有益于；有助于\nuseful  adj.有用的，有益的","0"));
        dao.add(new Word("145","lens","/lenz/","n. 透镜，镜头；眼睛中的水晶体；晶状体；隐形眼镜；汽车的灯玻璃\nvt. 给……摄影","This lens helps me see small things.\n这块镜片可以帮我看到很小的东西。","[串记] contact lens  隐形眼镜片\nmagnifying lens  放大镜","0"));
        dao.add(new Word("146","alarm","/ə'lɑːm/","n. 闹钟；警报，警告器；惊慌\nvt. 警告；使惊恐","My alarm wakes me up every day. I hate it so much.\n每天都被我的闹钟吵醒，恨死它了。","[对比] alarm/fear/panic均有“恐惧，惧怕、惊恐”之意。\nalarm：强调突然意识到有危险而产生的恐惧心理。\nfear：侧重指面临危险或灾祸时内心所引起的恐惧心情。\npanic：常指因突如其来的外界威胁使人群出现惊慌、恐惧或混乱。","0"));
        dao.add(new Word("147","insure","/ɪn'ʃɔː; ɪn'ʃʊə/","vt. 确保，保证；给…保险\nvi. 确保；投保","I insure my car against accident and theft.\n我为我的车上了事故险和偷盗险。","[对比] insure/assure/ensure均有“确保，保证”之意。\ninsure：指保险公司对于财产或者人身安全的保险。\nassure：就是主观上确保、确定某些事会发生，更强调保证。\nensure：也是确保，比较正式的场合，而且不是主观上认为，而是客观上。","0"));
        dao.add(new Word("148","shield","/ʃiːld/","n. 盾；防护物；保护者\nvt. 遮蔽；包庇；避开；保卫\nvi. 防御；起保护作用","The knight fights with a sword and shield.\n骑士挥舞着宝剑和盾牌战斗。","[对比] defend/harbour/shield均有“保护，保卫”之意。\ndefend：指用力或其他措施使人或物不不受损失，消除危险，\nharbour：贬义词，指隐匿或非法保护、窝藏。\nshield：侧重防止迫在眉睫的攻击或伤害。","0"));
        dao.add(new Word("149","expand","/ɪk'spænd; ek-/","vt. 扩张；使膨胀；详述\nvi. 发展；张开，展开","As the boy blows air in, the balloon expands.\n随着男孩儿往里吹气，气球膨胀了。","[对比] augment/amplify/enlarge/expand均有“扩大”之意。\naugment：一般指原来的基础上增加含量而扩大。\namplify：在科技中常指声音的扩大等。\nenlarge：主要指面积或体积的扩大。\nexpand：指范围、程度、体积和尺寸等面积的扩大或增加。","0"));
        dao.add(new Word("150","attractive","/ə'træktɪv/","adj. 吸引人的；有魅力的；引人注目的","Oh, my lady! You are so attractive!\n哇哦，我的女神！你简直太妩媚动人了！","[串记] attract  v.吸引，引诱\nattractive  adj.吸引人的，有魅力的\nattraction  n.吸引，吸引力，具有吸引力的事物","0"));

        dao.add(new Word("151","assume","/ə'sjuːm/","vi. 假定；设想；承担；采取\nvt. 僭取；篡夺；夺取；擅用；侵占","I don't know who you are, but I can assume you're my wife.\n我不知道你是谁，但我猜你是我的妻子。","[对比] assume/presume/suppose区别:\nassume：指有很少或完全无根据的武断推测或不合逻辑的推理。\npresume：侧重以过去经验或根据现实的某些感觉把某事认定为是事实。\nsuppose：指缺乏确切事实，根据一些现象进行得推测。","0"));
        dao.add(new Word("152","concentrate","/'kɒns(ə)ntreɪt/","vi. 集中；浓缩；全神贯注；聚集\nvt. 集中；浓缩\nn. 浓缩，精选；浓缩液","If you want to hit the target, you will have to concentrate and focus.\n如果你想射中靶子，你必须做到集中精神和专注。","[串记] concentrate/focus区别:\nconcentrate：指把人或事物集中在一起，也可指把精力或注意力集中与某一事物上。\nfocus：侧重把光、热、射线等集中于某一点，也把思想或精力集中于某人。","0"));
        dao.add(new Word("153","addition","/ə'dɪʃ(ə)n/","n. 添加；[数] 加法；增加物","Simple addition is the easiest part of math class.\n加法是数学里最简单的部分。","[串记] additional  adj.增加的, 附加的, 追加的\nadditive  n.添加剂，添加物  adj.附加的；[数] 加法的\nin addition  另外\nin addition to 除了...之外","0"));
        dao.add(new Word("154","beam","/biːm/","n. 横梁；光线；电波；船宽；[计量] 秤杆\nvt. 发送；以梁支撑；用…照射；流露\nvi. 照射；堆满笑容","A sun beam reaches down through the clouds.\n阳光穿过云层。","[对比] laugh/giggle/beam区别:\nlaugh：指因喜悦、愉快或轻视而出声的笑或大笑。\ngiggle：指发出咯咯的笑声，较多地用于女人或孩子。\nbeam：书面用语，指人因心情舒畅而发出的笑，即喜形于色地笑。","0"));
        dao.add(new Word("155","primitive","/'prɪmɪtɪv/","adj. 原始的，远古的；简单的，粗糙的\nn. 原始人","His car is so primitive, its wheels are made of rock!\n他的车很原始，车轮都是石头做的。","[串记] prime  adj.首要的，主要的  n.青春，全盛期\nprimary  adj.基本的，首要的\nprimitive  adj.原始的，简单的","0"));
        dao.add(new Word("156","salary","/'sælərɪ/","vt. 给...加薪；给...薪水\nn. 薪水","He said he'd double my salary if I work for him!\n他说要是我为他工作就付我双倍的工资。","allowance/earnings/salary均有“工资，收入”之意。\nallowance：指收入中的补贴部分。\nearnings：多指通过劳动或投资等手段所得到的收入。\nsalary：指按年定下，按月或星期平均给予的报酬，指脑力劳动者的薪水。","0"));
        dao.add(new Word("157","whereas","/weər'æz/","conj. 然而；鉴于；反之","The line chart shows one thing, whereas the bar chart shows another.\n线状图表现了一件事，然而柱状图表现了另一件事。","[串记] whereas/however均有“然而”之意。\nwhereas：用在句中\nhowever：用在句首。","0"));
        dao.add(new Word("158","prohibit","/prə(ʊ)'hɪbɪt/","vt. 阻止，禁止","The law prohibits spitting in public.\n该法令禁止在公共区域随意吐痰。","[对比]  ban/forbid/prohibit均有“禁止”之意。\nban：指合法地或由于社会压力而禁止，含谴责或不赞同的态度。\nforbid：比prohibit通俗，用于较小事物，或个人、上级、官方、长辈做出的禁止命令和规定，或客观条件不允许。\nprohibit：指通过法律、法令、警告等做出禁止命令的正式规定，prohibit sb from sth/doing sth。","0"));
        dao.add(new Word("159","project","/prəˈdʒekt; ˈprɒdʒekt/","vi. 设计；计划；表达；投射\nvt. 设计；计划；发射；放映\nn. 工程；计划；事业","The construction project is moving quickly.\n这个建筑工程进展迅速。","[联想] ject “扔”\npro 向前+ject 扔 -> 向前扔->投射，投影","0"));
        dao.add(new Word("160","stroke","/strəʊk/","n. （游泳或划船的）划；中风；（打、击等的）一下；冲程；（成功的）举动；尝试；轻抚\nvt. （用笔等）画；轻抚；轻挪；敲击；划尾桨；划掉；（打字时）击打键盘\nvi. 击球；作尾桨手，指挥划桨；（打字时）击打键盘","The stroke of his club sent the ball flying high in the air.\n他球杆这一击把球送上了高高的天空。","[串记] stake  n.木桩，赌注，利害关系\nstack  n.堆，一大堆  v.堆积，堆放\nstuck  adj.被卡住的；不能动的\nstruck  adj.受罢工影响的  v.罢工，打","0"));

        dao.add(new Word("161","fancy","/'fænsɪ/","n. 幻想；想象力；爱好\nadj. 想象的；奇特的；昂贵的；精选的\nvt. 想象；喜爱；设想；自负\nvi. 幻想；想象","The wedding was very fancy; there were flowers everywhere. \n婚礼很昂贵，到处都摆满了鲜花。","[对比] imagination/fancy均有“想象，幻想”之意。\nimagination：可指认真、带有启发性的想象，也可指凭记忆的想象或凭空想象事物的能力。\nfancy：指脱离实际的幻想或想象力，常暗含所想象的东西近乎怪诞的意味。","0"));
        dao.add(new Word("162","perceive","/pə'siːv/","vt. 察觉，感觉；理解；认知\nvi. 感到，感知；认识到","He perceived the sound even though he was far away.\n这即使他离得很远，他还是察觉到了声音。","[串记] perceive  v.意识到，察觉，发觉\nconceive  vi. 想到，怀孕  vt.想到，想像\nreceive  vt.收到；得到；接待\ndeceive  v.欺骗","0"));
        dao.add(new Word("163","economic","/,iːkə'nɒmɪk; ek-/","adj. 经济的，经济上的；经济学的","The people of China and India have worked hard for their economic success.\n中国和印度的人民为了他们经济上的成功一直努力奋斗。","[对比] 共同释义：经济的，财务的\neconomic：除指经济的外，还表示经济上有收益的，有利可图的\neconomical：指节约的，精打细算的\nfinancial：指财政的，财务的，财力的\neconomy：作形容词用在名词前面，构成名词短语，含义相当于economical。","0"));
        dao.add(new Word("164","minimum","/'mɪnɪməm/","n. 最小值；最低限度；最小化；最小量\nadj. 最小的；最低的","The boss pays me minimum wage; I wish he would pay me more!\n老板给我发了最低薪水，我希望他能多付我点。","[串记] maximum  最大值\nminimum  最小值\noptimum  最适宜\nmaximize  最大化\nminimize  最小化","0"));
        dao.add(new Word("165","current","/'kʌr(ə)nt/","adj. 现在的；流通的，通用的；最近的；草写的\nn. （水，气，电）流；趋势；涌流","\"Is the news current?\" \"No, it's from yesterday.\"\n“这是最新的新闻吗？” “不，这是昨天的了。”","[串记] currency  n.货币，流通，流行\ncurrent  adj.当前的，流行的  n.流，思潮\naccurate  adj.精确的，正确的，符合标准的\ncorrect  adj.正确的  v.改正","0"));
        dao.add(new Word("166","strain","/streɪn/","n. 张力；拉紧；负担；扭伤；血缘\nvi. 拉紧；尽力\nvt. 拉紧；滥用；滤去；竭力\nn. （植物、动物的）品种；种类","Taxes are too high--I can't handle the strain.\n税收太高了，我承受不起这么大的负担。","[串记] sprain  v.扭伤  n.扭伤\nstain  v.玷污，染色  n.染色，污迹\nstrain  n.负担，紧张  v.拉紧\nrestrain  v.制止（做），抑制\nconstrain  v.约束，强迫，限制","0"));
        dao.add(new Word("167","civil","/'sɪv(ə)l; -ɪl/","adj. 公民的；民间的；文职的；有礼貌的；根据民法的","Voting is an important civil right.\n选举权是一项重要的公民权利。","[串记] civic  adj.城市的；公民的，市民的\ncivil  adj.公民的，民用的；国内的\ncivility  n.礼貌; 礼仪; 端庄\ncivilian  n.平民，百姓  adj.平民的\ncivilization  n.文明","0"));
        dao.add(new Word("168","mood","/muːd/","n. 情绪，语气；心境；气氛","\"I'm in a good mood today,\" she said with a smile.\n“我今天心情很好，”她微笑着说。","[串记] be in a mood  在生气，心情不好\nbe in no mood for sth/to do sth  不想做某事\nbe in the mood  心情舒畅，来劲儿\ncatch the mood of sb  迎合某人一时一地的情绪","0"));
        dao.add(new Word("169","figure","/'fɪgə/","n. 数字；人物；图形；价格；（人的）体形；画像\nvi. 计算；出现；扮演角色\nvt. 计算；认为；描绘；象征","I maintain my figure by eating well and exercising.\n我通过合理膳食和锻炼保持身材。","[串记] figure on  指望\nfigure in  扮演...的角色\nfigure out  算出","0"));
        dao.add(new Word("170","assess","/ə'ses/","vt. 评定；估价；对…征税","It's her job to assess her patient's health.\n她的工作就是评估病人健康。","[串记] access  n.接近；通道，入口  v. 接近\nasset  n.财产，资产\nassert  vt.断言，肯定地说，坚持，维护\npossess  v.拥有，占有，(鬼等)缠\nassess  vt.评定；估价；对…征税","0"));

        dao.add(new Word("171","misunderstand","/,mɪsʌndə'stænd/","vt. 误解；误会","I think he misunderstands the recipe.\n我认为他误解了食谱（上的做法）。","[串记] understand  v.理解，推断，熟悉\nmisunderstand  vt.误解；误会","0"));
        dao.add(new Word("172","incident","/'ɪnsɪd(ə)nt/","n. 事件，事变；插曲\nadj. [光] 入射的；附带的；易发生的，伴随而来的","I have never seen such an unusual incident in my life.\n我长这么大从没见过这么不同寻常的事件。","[对比] accident和incident的区别：\naccident：强调偶然或意外发生的不幸事情。\nincident：既可指小事情或者附带事情，也可指政治上具有影响力的事情或者事变。","0"));
        dao.add(new Word("173","revenue","/'revənjuː/","n. 税收，国家的收入；收益","The company's revenues increase every year.\n每年公司的收入都在增加。","[对比] revenue：比较正式，通常用于企业，国家的销售总额，会计上指企业的营业收入，也指国家的税收。\nincome：比较口语，可以指公司也可以指个人，指公司往往指net profit。","0"));
        dao.add(new Word("174","regardless","/rɪ'gɑːdlɪs/","adj. 不管的；不顾的；不注意的\nadv. 不顾后果地；不管怎样，无论如何；不惜费用地","The couple kissed regardless of the fact that the kid was watching.\n这对情侣亲吻的时候，完全不顾有个孩子正在看着（他们）。","[串记] regardless  adj.不管的  adv.不顾后果地\nirrespective  adj.无关的；不考虑的\nneglect  v.忽视；忽略  n.忽视","0"));
        dao.add(new Word("175","lower","/'ləʊə/","vt. 减弱，减少；放下，降下；贬低\nvi. 降低；减弱；跌落\nadj. 下游的；下级的；下等的","The red arrow is going lower and lower.\n红色箭头降低再降低。","[串记] low  adj.低的，矮的\nlower  adj.较低的  v.减弱，减少\nflower  n.花","0"));
        dao.add(new Word("176","regard","/rɪ'gɑːd/","n. 注意；尊重；问候；凝视\nvt. 注重，考虑；看待；尊敬；把…看作；与…有关\nvi. 注意，注重；注视","I regard my teacher with respect.\n我很尊敬我的老师。","[对比] admiration/respect/regard均有“尊敬，敬意”之意。\nadmiration：指除表示尊敬外，还常伴随有一种真挚的倾慕之情。\nrespect：指对年长、地位较高的人的尊敬，对他人成就、行为或见解等经过仔细评估后而表示尊敬。\nregard：最正式用词，与respect与honor近义。","0"));
        dao.add(new Word("177","adopt","/ə'dɒpt/","vt. 采取；接受；收养；正式通过\nvi. 采取；过继","This is the attitude that everyone should adopt towards their frustrations. \n这也是每个人面对挫折时应该采取的态度。","[串记] adoption  n.采用，采纳，收养\nadapt  v.适应不同情况\nadaptation  n.适应，改编，改写本\nadept  n.专家，能手  adj. 熟练的\nabode  n.住处，住所","0"));
        dao.add(new Word("178","significant","/sɪg'nɪfɪk(ə)nt/","adj. 重大的；有效的；有意义的；值得注意的；意味深长的\nn. 象征；有意义的事物","This day is significant for me because it's my father's birthday.\n这一天对我意义重大，因为这天是我爸爸的生日。","[对比] significant/important/vital均有“重要的”之意。\nsignificant：表示该事件非常突出及有优越性。\nimportant：强调某事值得重视。\nvital：表示极其重要，生死攸关。","0"));
        dao.add(new Word("179","technology","/tek'nɒlədʒɪ/","n. 技术；工艺；术语","With the remarkable development of technology, telephones get smaller.\n随着科技日新月异，电话越来越小了。","[串记] technique  n.技巧，技能，技艺\ntechnical  adj.技术的，工艺的\ntechnician  n.技术员，技师\ntechnology  n.技术；工艺","0"));
        dao.add(new Word("180","clarify","/'klærɪfaɪ/","vt. 澄清；阐明\nvi. 得到澄清；变得明晰；得到净化","I didn't understand, so I asked him to clarify what he wrote.\n我不明白，所以我让他解释他写的什么。","[对比] account/explain/clarify区别:\naccount：说明某事物如何符合自然法则或逻辑。\nexplain：指把某事向原来不了解、不清楚的人解释明白、说清楚。\nclarify：指把已经发生的事件、情况和现状说清楚。","0"));

        dao.add(new Word("181","resort","/rɪ'zɔːt/","n. 凭借，手段；度假胜地；常去之地\nvi. 求助，诉诸；常去；采取某手段或方法","The beachside resort has a swimming pool.\n这家海滨度假村有一个游泳池。","[串记] sort  v.整理，把...分类  n.种类\nresult  n.结果  v.起因，由于\nreport  n/v.报告，汇报，报道\nretort  v/n.反驳，反击\nresort  n. 凭借，度假胜地  vi.求助，常去","0"));
        dao.add(new Word("182","cite","/saɪt/","vt. 引用；传讯；想起；表彰","\"I'm going to have to cite you for driving too fast.\"\n“我不得不因你超速驾驶而指控你。”","[对比] recite  v.背诵，朗诵\nsite  n.地点，网站，现场  vt.给…造址\ncite  v.引用，引证\nquote  v.引述","0"));
        dao.add(new Word("183","attach","/ə'tætʃ/","vt. 使依附；贴上；系上；使依恋\nvi. 附加；附属；伴随","You should attach your name to your luggage in case it gets lost.\n为了以防万一，你应该把你的名字系在行李上。","[联想] 附上（attach）一个有吸引的（attractive）的附件（attachment）去尝试（attempt）进行进攻（attack）。","0"));
        dao.add(new Word("184","transmit","/trænz'mɪt; trɑːnz-; -ns-/","vt. 传输；传播；发射；传达；遗传\nvi. 传输；发射信号","The tower transmits the TV signal.\n这座塔负责传送电视信号。","[串记] transmission  n.发射，转播，传播\ntransmit  v.传送；传播；发射\ntransit  n. 运输，运送\ntransport  n.运输，运输工具  vt.运输\ntransform  v.将…变形，变化","0"));
        dao.add(new Word("185","continual","/kən'tɪnjʊəl/","adj. 持续不断的；频繁的","The continual washing of the waves has reduced the stones of this beach to sand.\n随着波浪不断的洗刷，沙滩上的石头渐渐碎成了沙子。","[串记] usual  adj.通常的，惯常的\ncontinue  v.继续，连续，延伸\ncontinual  adj.不断的，连续的\ncontinually  adv.不断地，连续地","0"));
        dao.add(new Word("186","proof","/pruːf/","n. 证明；证据；校样；考验；验证；试验\nadj. 防…的；不能透入的；证明用的；耐…的\nvt. 试验；校对；使不被穿透","We have proof that you're sick.\n我们有证据表明你生病了。","[串记] affirm  v.断定，肯定\nwitness  n.目击者，见证人  v.目击\nproof  n.证据，证明  v.校验\nroof  n.屋顶，顶部\nwaterproof  adj.防水的","0"));
        dao.add(new Word("187","principle","/'prɪnsɪp(ə)l/","n. 原理，原则；主义，道义；本质，本义；根源，源泉","Our business success is based on four fundamental principles.\n我们生意的成功是基于四项基本的原则。","[串记] in principle  原则上\non principle  按照原则","0"));
        dao.add(new Word("188","enhance","/ɪn'hɑːns; -hæns; en-/","vt. 提高；加强；增加","If you teach us how to use computers, it will enhance our productivity.\n如果你教会我们用电脑，我们的生产力就会得到提高。","[对比] enhance：侧重指增加价值、魅力等使人或者物具有非常寻常的吸引力。\nheighten：指使某物的某些性质变得不同于一般的显著或者突出。\nintensity：指深化或者强化某事或某物，尤指特别之处。\naggravate：指加剧令人不快或者困难的形式。","0"));
        dao.add(new Word("189","issue","/'ɪʃuː; 'ɪsjuː/","n. 问题；流出；期号；发行物\nvt. 发行，发布；发给；放出，排出\nvi. 发行；流出；造成…结果；传下","The issues found in my project made me frustrated！\n我项目中的一些问题让我头大！","[串记] at issue  争议中的，讨论中的\nmake an issue of sth  使...引起关注\ntake issue with sb/sth  对...持异议\nhave issue with  在...方面有困难","0"));
        dao.add(new Word("190","frame","/freɪm/","n. 框架；结构；[电影] 画面\nvt. 设计；建造；陷害；使…适合\nvi. 有成功希望\nadj. 有木架的；有构架的","The picture looks nice in this picture frame.\n这幅画在这面画框里看起来很漂亮。","[联想] 很有名望（fame）的人，将照片镶在框（frame）中。","0"));

        dao.add(new Word("191","consistent","/kən'sɪst(ə)nt/","adj. 始终如一的，一致的；坚持的","All the pipes are of a consistent size.\n所有的管子都是一样的尺寸。","[串记] consist  v.由…组成，存在\nconsistent  adj.一致的，一贯的","0"));
        dao.add(new Word("192","insert","/ɪn'sɜːt/","vt. 插入；嵌入\nn. 插入物；管芯；镶块；[机械]刀片","Just insert your credit card into the ATM and you will receive your money shortly.\n只要把卡插进取款机你就能很快取到钱了。","[串记] assertive  adj.肯定的；独断的；坚定而自信的\ndesert  n.沙漠  v.放弃\ninsert  vt.插入；嵌入  n. 插入物","0"));
        dao.add(new Word("193","complex","/'kɒmpleks/","adj. 复杂的；合成的\nn. 复合体；综合设施","Computers are so complex--I can't understand them at all.\n电脑好复杂，我完全不能理解！","[对比] complex/complicated均有“复杂的”之意。\ncomplex：侧重内在关系的复杂，需通过仔细研究与了解才能掌握和运用。\ncomplicated：比complex语气重，着重极其复杂，很难分析、分辨或解释。","0"));
        dao.add(new Word("194","company","/'kʌmp(ə)nɪ/","n. 公司；陪伴，同伴；连队\nvi. 交往\nvt. 陪伴","I like working for my company.\n我喜欢为我的公司工作。","[串记] firm  较小的公司\ncompany  公司\ncorporate  较大的公司\nenterprise  大集团","0"));
        dao.add(new Word("195","credit","/'kredɪt/","n. 信用，信誉；[金融] 贷款；学分；信任；声望\nvt. 相信，信任；把…归给，归功于；赞颂","It's better to use a credit card than to carry cash.\n刷信用卡比付现金要好。","[串记] credit card  信用卡\ngive credit to  相信...\ngive sb credit for sth  相信某人有...","0"));
        dao.add(new Word("196","neglect","/nɪ'glekt/","vt. 疏忽，忽视；忽略\nn. 疏忽，忽视；怠慢","The parents neglect their child so they can keep fighting.\n我们不会批评宗教或者宗教自由。那对父母忽视了他们的孩子，只顾着一直吵架。","[串记] irrespective  adj.无关的；不考虑的\nregardless  adj.不管的  adv.不顾后果地\nirrespective  adj.无关的；不考虑的\nneglect  v.忽视；忽略  n.忽视","0"));
        dao.add(new Word("197","stimulate","/'stɪmjʊleɪt/","vt. 刺激；鼓舞，激励\nvi. 起刺激作用；起促进作用","A good massage should stimulate the neck too.\n优质的按摩应该还要按摩颈部。","[串记] simulate  v.假装；模仿；模拟\nimitate  v.模仿\nstimulate  v.刺激，引起\nformulate  vt.用公式表示，系统地阐述\naccumulate  vi.聚积  vt.积攒，积累","0"));
        dao.add(new Word("198","conscious","/'kɒnʃəs/","adj. 意识到的；故意的；神志清醒的","I'm awake and conscious at 5 a.m. but I wish I wasn't.\n我在早上5点就完全清醒了，但是我多希望我没有。","[对比] conscious与aware的区别：\nconscious：通常比较正式，强调内心的意识。\naware：指通过信息，或感觉器官意识的。","0"));
        dao.add(new Word("199","tough","/tʌf/","adj. 艰苦的，困难的；坚强的，不屈不挠的；坚韧的，牢固的；强壮的，结实的\nn. 恶棍\nvt. 坚持；忍受，忍耐\nadv. 强硬地，顽强地","He looks like a tough guy--you don't want to fight with him.\n他看起来很强壮，你不会想要和他打架的。","[串记] touch  vt.触摸，感动  n.触\ntough  adj.坚韧的；健壮的\nrough  adj.粗糙的；大致的；粗暴的","0"));
        dao.add(new Word("200","expansion","/ɪk'spænʃ(ə)n; ek-/","n. 膨胀；阐述；扩张物","Our company has undergone steady expansion for the last ten years.\n我们的公司在过去的十年中实现了稳定的扩展。","[串记] expand  vi. 膨胀，展开，扩大\nexpanse  n.宽阔；广阔的区域；苍天\nexpend  v.消费，用尽\nextend  v.延伸，延长，扩展\nextension  n.延长部分，伸展","0"));

        dao.add(new Word("201","congress","/'kɒŋgres/","n. 国会；代表大会；会议；社交","In America, the Congress writes laws. \n在美国，由国会制定法律。","[对比] congress：指国会议会等代表大会的机构。\nconference：指各种大型会议、政府、学术。\nconvention：侧重某一政党或团体为某一特殊目的召开的会议，也指学术团体的年会。","0"));
        dao.add(new Word("202","symbol","/'sɪmb(ə)l/","n. 象征；符号；标志","These symbols represent all the different things our software can do.\n这些图标代表了我们的软件能做的所有不同的功能。","[对比] symbol/sign/token均有“符号，标志”之意。\nsymbol：指作象征或表达某种深邃意蕴的特殊事物。\nsign：指人们公认事物的记号，也可指某种情况的征兆。\ntoken：指礼品、纪念物等作为表示友谊、爱情等的象征或标志。","0"));
        dao.add(new Word("203","stuff","/stʌf/","n. 东西；材料；填充物；素材资料\nvt. 塞满；填塞；让吃饱\nvi. 吃得过多","We keep all of the baby's stuff in his bedroom.\n我们把孩子所有的东西都放在他的卧室里。","[串记] stuff of sth  基本特征，特质\ndo your stuff  施展自己的本事\nnot give a stuff  一点不在乎\nstuff and nonsense  废话，胡说八道","0"));
        dao.add(new Word("204","observe","/əb'zɜːv/","vt. 庆祝\nvt. 观察；遵守；说；注意到；评论\nvi. 观察；说；注意到；评论","She observes the liquid very carefully.\n她观察液体时十分仔细。","[串记] observe  v.注意，观察，遵守\nreserve  n.储备，后备  v.储备，保留\ndeserve  v.应得，应受\npreserve  v.保护，保存","0"));
        dao.add(new Word("205","confident","/'kɒnfɪd(ə)nt/","adj. 自信的；确信的","The girl was confident that she could defeat all the other players.\n小女孩儿自信能够打败所有其他选手。","[串记] confident  n.知己  adj.确信的\nconfidence  n.信任，自信  adj.值得信任的\nconfidential  adj.机密的，表示信任的\nconfidant  n.密友\nconfide  v.倾诉，委托，信赖","0"));
        dao.add(new Word("206","association","/əˌsəʊsɪˈeɪʃn/","n. 协会，联盟，社团；联合；联想","Our association has many members with different skills.\n我们的协会里有很多拥有不同技能的成员。","[串记] associate  \nassociative  v.联接；联想  n. 伙伴，同事\nassociable  adj.可联想的；交感性的\nassociationism  n.联想心理学；观念联合论\nassociational  adj.联想的；协会的","0"));
        dao.add(new Word("207","install","/ɪnˈstɔ:l/","vt. 安装；任命；安顿","The man installs a ceiling fan.\n这男人把吊扇装上了。","[串记] installment  n.分期付款，部分\nuninstall  v.卸载\ninstore  adj.库存的，仓库内的\ninstill  vt.徐徐滴入，逐渐灌输","0"));
        dao.add(new Word("208","necessity","/nɪ'sesɪtɪ/","n. 需要；必然性；必需品","Water is a necessity for life.\n水是生命的必需品。","[串记] necessary  n.必需品  adj.必要的，必需的\nnecessity  n.需要，必需品，必要性\nnecessarily  adv.必然，必定\nnecessitate  vt.使成为必需，需要；迫使","0"));
        dao.add(new Word("209","spot","/spɒt/","n. 地点；斑点\nvt. 认出；弄脏；用灯光照射\nvi. 沾上污渍；满是斑点\nadj. 现场的；现货买卖的\nadv. 准确地；恰好","The artist made a pattern of blue spots on the white wall.\n艺术家在白墙上弄上了蓝色斑点。","[串记] blot  n.污点；缺点  v. 涂污\nmark  v.做记号于，标明  n.分数，污点\nspot  n.斑点，污点  v. 发现，认出\nstrain  n.负担，紧张  v. 拉紧","0"));
        dao.add(new Word("210","affect","/ə'fekt/","vt. 影响；感染；感动；假装\nvi. 倾向；喜欢\nn. 情感；引起感情的因素","Her break up with her lover has badly affected her.\n她与恋人的分手严重地影响了她。","[对比] affect/influence/impress区别:\naffect：做主语通常是物而不是人，指一物对另一物产生的消极影响。\ninfluence：侧重在思想、性格、行为等方面所产生的潜移默化的影响，也可指自然力的影响。\nimpress：强调影响既深刻又持久。\n","0"));

        dao.add(new Word("211","trial","/'traɪəl/","n. 试验；审讯；努力；磨炼\nadj. 试验的；审讯的","After the trial, the judge found the prisoner guilty.\n审判后，法官判定犯罪嫌疑人有罪。","[串记] trial  n.试验，磨炼  adj.试验的\ntrail  n.小径，记号  v.追赶\ntail  n.尾巴，末端  v. 紧跟，尾随","0"));
        dao.add(new Word("212","harmony","/'hɑːmənɪ/","n. 协调；和睦；融洽；调和","The Yin-Yang is a symbol of harmony.\n阴阳是和谐的一种象征。","[对比] harmony/agreement/concord/unity均有“和谐”之意。\nharmony：指人与人之间或不同部分与整体之间完全协调、和谐、愉快。\nagreement：侧重态度与观点的一致。\nconcord：多指人际、国家间或民族之间协调一致的关系。\nunity：指各个成员、各群体之间相互协调一致的关系。","0"));
        dao.add(new Word("213","gesture","/'dʒestʃə/","n. 姿态；手势\nvi. 作手势；用动作示意\nvt. 用动作表示","Their \"thumbs up\" gesture meant that they liked it.\n竖起大拇指的手势表示他们喜欢这东西。","[串记] posture  n.姿势，姿态，看法\nattitude  n.姿势，态度，意见\ngesture  n.手势，表情  v.做手势","0"));
        dao.add(new Word("214","undergo","/ʌndə'gəʊ/","vt. 经历，经受；忍受","The woman will undergo surgery to cure her disease.\n这个女人得经过手术来治疗她的疾病。","[对比] undergo/experience/sustain/suffer均有“经历，遭受”之意。\nundergo：多指经受艰难、痛苦、不愉快或危险等事。\nexperience：指亲身经受或体验某事。\nsustain：指遭受痛苦或承受负担。\nsuffer：指被迫忍受痛苦。","0"));
        dao.add(new Word("215","engage","/ɪn'geɪdʒ; en-/","vt. 吸引，占用；使参加；雇佣；使订婚；预定\nvi. 从事；答应，保证；交战；啮合","They are engaged; you should see the ring he gave her!\n他们订婚了。你应该看看他送她的戒指！","[串记] engage with  与...接洽\nengage sb  雇佣\nengage sb in  使加入\nengage in  从事于\nengage to do  保证","0"));
        dao.add(new Word("216","unique","/juˈnik/","adj.独特的，独一无二的\n adj.(唯一的) 特有的","Fingerprints are unique to each individual.\n每个人的指纹都是独一无二的。","[串记] unique  adj.独特的，独一无二的\nsole  adj.惟一的  n.脚底  v.装鞋底\ndistinctive  adj.有特色的，与众不同的\nindividual  n.独立的个体  adj.个别的，独特的","0"));
        dao.add(new Word("217","annual","/'ænjʊəl/","adj. 年度的；每年的\nn. 年刊，年鉴；一年生植物","2012's annual budget has been prepared by the government.\n2012年的年度预算已经被政府筹备好了。","[串记] annual  n.一年一度的事件  adj.年度的，全年的\nannul  v.取消，废除，宣告无效\nanniversary  n.周年纪念日  adj.周年的","0"));
        dao.add(new Word("218","barrier","/'bærɪə/","n. 障碍物，屏障；界线\nvt. 把…关入栅栏","The road was closed by a barrier.\n这条路设置了路障，被封锁了。","[对比] obstacle/barrier/obstruction均有“障碍物”之意。\nobstacle：指在达到目的或前进的过程中必须消除或绕过的障碍物，也指起阻碍作用的情况。\nbarrier：常指临时地或者可能跨越的障碍。\nobstruction：常指具体的障碍又可指抽象或寓意上的阻碍。","0"));
        dao.add(new Word("219","budget","/'bʌdʒɪt/","n. 预算，预算费\nvt. 安排，预定；把…编入预算\nvi. 编预算，做预算\nadj. 廉价的","Our budget for this year is too small for us to buy a house.\n我们今年的预算太少了不够买房子。","[串记] barge  n.平底货船，驳船\nbadge  n.徽章，象征  vt.给予…标记\nbudge  v.移动一点；妥协\nbudget  n.预算  v.预算，安排  adj.廉价的","0"));
        dao.add(new Word("220","pace","/peɪs/","n. 一步；步速；步伐；速度\nvi. 踱步；缓慢而行\nvt. 踱步于；用步测","The horse walked at a fast pace.\n马以很快的步速走着。","[对比] speed/velocity/pace/step均有“速度，速率”之意。\nspeed：指单位时间内进行得固定速度。\nvelocity：技术用词，指物体沿着一定方向运动时的速率。\npace：指步行的速度，常引申指活动的进度或生产率。\nstep：指脚抬起落下的动作和一步的距离。","0"));

        dao.add(new Word("221","mere","/mɪə/","adj. 仅仅的；只不过的\nn. 小湖；池塘","His lunch is a mere berry.\n他午饭仅仅吃了一颗浆果。","[串记] merely  adv.仅仅，只不过\nbarely  adv.仅仅，只不过，几乎不\nrarely  adv.很少，难得","0"));
        dao.add(new Word("222","media","/'miːdɪə/","n. 媒体；媒质（medium的复数）；血管中层；浊塞音；中脉","These days we get our information from all kinds of different media.\n如今我们从各种不同的媒体获取信息。","[串记] medium  n.中间物，媒介物 adj. 中等的\nmediate  v.调解，调停\nimmediately  adv.直接地，立即","0"));
        dao.add(new Word("223","upset","/ʌp'set/","vt. 使心烦；颠覆；扰乱\nvi. 翻倒\nadj. 心烦的；混乱的；弄翻的\nn. 混乱；翻倒；颠覆","She was really upset after her presentation to the class didn't go well.\n在班上做完不理想的报告以后，她很沮丧。","[对比] upset：侧重失去精神上的平静，心理上完全丧失平衡。\nagitate：侧重指内心的焦虑，难于控制，表露于外。\ndisturb：指因某人的行动、扰乱、妨碍安静等而使人不得安宁。","0"));
        dao.add(new Word("224","facility","/fə'sɪləti/","n. 设施；设备；容易；灵巧","This facility contains many different kinds of products.\n这间车间有很多不同种类的产品。","[串记] facility  n.设施；设备；容易；灵巧\nfacilitate  vt.使便利，促进\nfaculty  n.能力；系，科；教职工\ncapability  n.(实际)能力，性能，容量","0"));
        dao.add(new Word("225","remedy","/'remɪdɪ/","vt. 补救；治疗；纠正\nn. 补救；治疗；赔偿","This plant contains a remedy for your sickness.\n这种植物对你的病有疗效。","[对比] cure/treat/heal/remedy均有“治疗”之意。\ncure：主要指治愈疾病。\ntreat：指接受并诊治病人。\nheal：侧重指治愈伤口、伤痛如灼伤等。\nremedy：着重用药物对病人进行治疗。","0"));
        dao.add(new Word("226","prompt","/prɒm(p)t/","adj. 敏捷的，迅速的；立刻的\nvt. 提示；促进；激起；（给演员）提白\nn. 提示；付款期限；DOS命令：改变DOS系统提示符的风格\nadv. 准时地","The boss prompts his employees to walk forward.\n这个老板敦促他的员工不断前进。","[串记] prompt sb to do sth  促使某人做某事\npromote  v.促进，提升；发扬","0"));
        dao.add(new Word("227","relationship","/rɪ'leɪʃ(ə)nʃɪp/","n. 关系；关联","The husband and wife had a very close relationship.\n丈夫和妻子有很亲密的关系。","[联想] relation  意为关系\nship  意为小船\n关系的小船（relationship）说翻就翻。","0"));
        dao.add(new Word("228","complicated","/'kɒmplɪkeɪtɪd/","adj. 难懂的，复杂的","Geometry is a very complicated subject--it makes my head hurt.\n几何是一门非常复杂的学科，让我很头疼。","[对比] complex/complicated均有“复杂的”之意。\ncomplex：侧重内在关系的复杂，需通过仔细研究与了解才能掌握和运用。\ncomplicated：比complex语气重，着重极其复杂，很难分析、分辨或解释。","0"));
        dao.add(new Word("229","ease","/iːz/","vt. 减轻，缓和；使安心\nn. 轻松，舒适；安逸，悠闲\nvi. 减轻，缓和；放松；灵活地移动","Lying in the grass gives her a feeling of ease and comfort.\n躺在草地上让她轻松舒适。","[串记] disease  n.疾病\nat ease  舒适的、安逸的\neasy  adj.容易的；安逸的\ntake it easy  放轻松","0"));
        dao.add(new Word("230","approve","/ə'pruːv/","vt. 批准；赞成；为…提供证据\nvi. 批准；赞成；满意","They all approve of my good performance.\n他们都称许我良好的表现。","[串记] prove  v.证明，检验，结果是\napprove  v.赞成，称许，批准\nimprove  v.改善，增加","0"));

        dao.add(new Word("231","online","/ɒn'laɪn/","adj. 联机的；在线的\nadv. 在线地","I put my family photos online to share with my friends.\n我把我的全家福放在网上来和我的朋友们分享。","[串记] underline  v.划线于…之下，强调\noffline  n.脱机  adj.离线的  adv.未连线地\nincline  n.斜坡  v.倾斜，使倾向于\nbaseline  n.基线；底线\noutline  n.轮廓  vt.概述；略述","0"));
        dao.add(new Word("232","determine","/dɪ'tɜːmɪn/","v. （使）下决心，（使）做出决定\nvt. 决定，确定；判定，判决；限定\nvi. 确定；决定；判决，终止；[主用于法律]了结，终止，结束","I will determine which option is better.\n我将决定哪一个选项更好。","[对比] decide/determine/resolve/settle均有“决定”之意。\ndecide：侧重指经过考虑、比较、讨论或询问之后做出的决定。\ndetermine：指经过深思熟虑，决定去做某事并坚持施行。\nresolve：强调以坚定不移的信念去做某事，暗含有远大抱负和坚强决心。","0"));
        dao.add(new Word("233","invade","/ɪn'veɪd/","vt. 侵略；侵袭；侵扰；涌入\nvi. 侵略；侵入；侵袭；侵犯","We can use these tanks to invade another country.\n我们可以用这些坦克来侵略别的国家。","[串记] invade  v.侵略，侵犯\npervade  v弥漫，渗透\nevade  v.躲避，回避","0"));
        dao.add(new Word("234","senior","/'siːnɪə; 'siːnjə/","adj. 高级的；年长的；地位较高的；年资较深的，资格较老的\nn. 上司；较年长者；毕业班学生","Senior citizens should be respected.\n年长的人应该被尊重。","[串记] senior  adj.年长的，高级的\njunior  adj.年幼的，下级的\nfreshman  大一学生\nsophomore  大二学生","0"));
        dao.add(new Word("235","equivalent","/ɪ'kwɪv(ə)l(ə)nt/","adj. 等价的，相等的；同意义的\nn. 等价物，相等物","These two things are of equivalent weight.\n这两个东西是同样重的。","[串记] egalitarian  n.平等主义；平等主义者  adj.平等主义的\nequity  n.公平，公正\nequality  n.同等，平等，等式","0"));
        dao.add(new Word("236","relevant","/ˈreləvənt/","adj. 相关的；切题的；中肯的；有重大关系的；有意义的，目的明确的","The suggestion given was relevant to our problem.\n给出的这个建议与解决我们的问题相关。","[串记] relative  n.亲戚；相关物  adj.相对的；有关系的\nrelevant  adj.有关的，恰当的\nrelevance  n.关联；适当\nrelevancy  n.关联；恰当","0"));
        dao.add(new Word("237","deal","/diːl/","vt. 处理；给予；分配；发牌\nvi. 处理；讨论；对待；做生意\nn. 交易；（美）政策；待遇；份量","So we agree, you'll buy my house? Do we have a deal? good.\n那么你确定要买我的房子？我们说好了吧，很好！","[串记] a great deal  丰富，大量\na good deal  许多\nbig deal  重要，同important\ndeal with  处理","0"));
        dao.add(new Word("238","behavior","/bɪˈheɪvjə/","n. 行为，举止；态度；反应","His behavior in class has improved a lot over the past month.\n在过去的一个月里他在班里的举止改善很多。","[对比] behavior/conduct/manner均有“行为，举止”之意。\nbehavior：侧重指某人在特定场合对他人或在他人面前的表现得行为、举止。\nconduct：侧重根据社会道德标准和责任感。\nmanner：主要用来指人的习惯行为。","0"));
        dao.add(new Word("239","deaf","/def/","adj. 聋的","The old man is almost deaf, you have to talk very loudly to him.\n这个老男人几乎聋了，你对他说话必须很大声。","[串记] deaf  adj.聋的\nblind  adj.瞎的\nlame  adj.瘸的\ndumb  adj.哑的","0"));
        dao.add(new Word("240","crash","/kræʃ/","n. 撞碎；坠毁；破产；轰隆声；睡觉\nvi. 摔碎；坠落；发出隆隆声；(金融企业等)破产\nvt. 打碎；使坠毁、撞坏；擅自闯入","It was a serious car crash.\n这是一次严重的车祸。","[联想] 车子发生了crash（碰撞），被crush（压碎）了，要赔cash（现金）。","0"));

        dao.add(new Word("241","personality","/pɜːsə'nælɪtɪ/","n. 个性；品格；名人","I thought she was nice, but her real personality is much meaner.\n我以为她人很好，但是原来她真实的性格讨厌得多。","[对比] personality：指日常表现出来的性格。\ncharacter：指一个人真正的根深蒂固的，永久具有的内在的本质。\nnature：指天生的、无法改变的性格或品质。\ntemper：可做脾气，指心境的好坏。","0"));
        dao.add(new Word("242","permission","/pə'mɪʃ(ə)n/","n. 允许，许可","They gave me an American visa, so I now have permission to travel there.\n他们给了我一份美国签证，所以现在我有去那里的许可了。","[串记] permit  n.执照  vt.允许，许可\npermission  n.允许，同意\nadmit  v.承认；准许…进入\nadmission  n.准许进入，进入权","0"));
        dao.add(new Word("243","abortion","/ə'bɔːʃ(ə)n/","n. 流产，堕胎，小产；流产的胎儿；（计划等）失败，夭折","How moral is it to advertise something as sensitive as abortion?\n用堕胎这种敏感话题来打广告是不是有点违背道德？","[串记] abort  v.异常中断，中途失败，流产\nabortive  adj.无结果的，失败的\nabortionist  n.（尤指非法）为人堕胎者\nabortus  n.流产胎","0"));
        dao.add(new Word("244","flat","/flæt/","n.平面；公寓\nadj.平坦的；浅的；单调的\nadv.干脆地","My new flat screen TV takes up much less space.\n我的新平板电视占了很少的空间。","[对比] even/flat/level均有“平的，平坦的”之意。\neven：通常指平面上的各点或一条直线的各点处在同一平面或直线上。\nflat：指光滑平整的表面，但不一定是水平的。\nlevel：强调没有高低之分，且在同一水平面上。","0"));
        dao.add(new Word("245","eliminate","/ɪ'lɪmɪneɪt/","vt. 消除；排除","This device will eliminate the weeds in my garden.\n这个装置会除掉我花园里的杂草。","[串记] illuminate  v.照亮，阐明，启发\nimitate  v.模仿\nestimate  v.估计，评价  n. 估计","0"));
        dao.add(new Word("246","executive","/ɪgˈzekjʊtɪv/","adj. 行政的；经营的；执行的，经营管理的\nn. 总经理；执行委员会；执行者；经理主管人员","The executives of both companies discussed the issue in depth.\n双方公司的执行人员深入地讨论了这个问题。","[联想] chief executive officer （CEO）首席执行官，执行总裁","0"));
        dao.add(new Word("247","border","/'bɔːdə/","n. 边境；边界；国界\nvt. 接近；与…接壤；在…上镶边\nvi. 接界；近似","The border between the US and Canada is very long.\n美国与加拿大的国界线很长。","[串记] border  n.边缘，边界  v.接界\nboard  n.木板；董事会\naboard  prep.在 (船、火车、汽车、飞机等)上\nabroad  prep./adv.到国外，在国外，在外","0"));
        dao.add(new Word("248","sample","/'sɑːmp(ə)l/","vt. 取样；尝试；抽样检查\nn. 样品；样本；例子\nadj. 试样的，样品的；作为例子的","I'll need a sample of your blood to see if you're sick.\n我需要你血液样本来确定你是不是生病了。","[对比] case/example/sample均有“例子，事例”之意。\ncase：多指需要加以认真研究的实例。\nexample：指能代表同类事物性质或一般规律的典型例子。\nsample：通常指样品。","0"));
        dao.add(new Word("249","junior","/'dʒuːnɪə/","adj. 年少的；后进的；下级的\nn. 年少者，晚辈；地位较低者；大学三年级学生","'Junior' means young or younger.\n“少年”是指年少或者更小的孩子。","[串记] senior  adj.年长的，高级的\njunior  adj.年幼的，下级的\nfreshman  大一学生\nsophomore  大二学生","0"));
        dao.add(new Word("250","emphasize","/'emfəsaɪz/","vt. 强调，着重","The preacher emphasizes that the Devil wants us all.\n这个牧师一直强调魔鬼想要我们所有人。","[串记] emphasis  n.强调，重点，重要性\nemphasise  v.强调\nemphasize  v.强调","0"));

        dao.add(new Word("251","appointment","/əˈpɔɪntmənt/","n. 任命；约定；任命的职位","My doctor's appointment lasted thirty minutes.\n我和医生进行了30分钟的会面。","[串记] appoint  v.委派，任命；约定\nappointive  adj.任命的；委派的\nappointed  v.任命；指定  adj.约定的\nappointment  n.任命；约定","0"));
        dao.add(new Word("252","fare","/feə/","vi. 经营；进展；遭遇；过活\nn. 票价；费用；旅客；食物","The fare for this bus ride is $2.\n这一程巴士收费2美元。","[串记] tuition  学费\nfee  杂费\nallowance  津贴\nscholarship  奖学金\nfine  罚款\nrevenue  税收","0"));
        dao.add(new Word("253","capture","/'kæptʃə/","vt. 俘获；夺得；捕捉，拍摄,录制\nn. 捕获；战利品，俘虏","These panels capture the sun's radiation to make electricity.\n这些太阳能板捕捉太阳的辐射来产生电能。","[对比] arrest/capture/catch区别:\narrest：指根据法律或命令进行逮捕并予以监禁或拘留。\ncapture：指通过武力或计谋等，战胜抵抗而抓住敌人或动物。\ncatch：指捉住跑动或隐藏中的人或动物，一般指活捉。","0"));
        dao.add(new Word("254","judgement","/'dʒʌdʒm(ə)nt/","n. 意见；判断力；[法] 审判；评价","In the court's judgement, I was guilty.\n依法院判决，我是有罪的。","[串记] judge  n.裁判员  v.判决，审判\njudgement  n.意见；判断力\njustice  n.正义，公平，合理","0"));
        dao.add(new Word("255","numerous","/'njuːm(ə)rəs/","adj. 许多的，很多的","The stadium is filled with numerous sports fans.\n体育场里坐满了许多体育爱好者。","[串记] numerous  adj.许多的，很多的\nnumerable  adj.可计数的；可计算的\nnumerical  adj.数字的，用数字表示的\nnumeral  n.数字","0"));
        dao.add(new Word("256","immune","/ɪ'mjuːn/","adj. 免疫的；免于……的，免除的\nn. 免疫者；免除者","This shot will make you immune to all kinds of diseases.\n这一针会让你对某种疾病免疫。","[串记] immune  adj.免疫的  n.免疫者\nimmunochemistry  n.免疫化学\nimmunity  n.免疫力；豁免权；免除\nimmunization  n.免疫","0"));
        dao.add(new Word("257","measure","/'meʒə/","n. 测量；措施；程度；尺寸\nvt. 测量；估量；权衡\nvi. 测量；估量","Every week I measure my waist to see how much weight I've lost.\n每周我都量一下腰围来看我掉了多少斤肉。","[串记] treasure  n.金银财宝，财富  vt.珍藏，储藏\nmeasure  n.测量；措施  v.测量\nbeyond measure  无法估计，极度\ntake some measure  采取措施","0"));
        dao.add(new Word("258","profit","/'prɒfɪt/","n. 利润；利益\nvi. 获利；有益\nvt. 有益于","Profits have increased year on year. \n利润连年增长。","benefit/interest/profit均有“利益、好处”之意。\nbenefit：指通过正当手段从物质或精神方面得到的任何好处或利益。\ninterest：既可指集团、群体的利益，又可指个人利益。\nprofit：指从物质、钱财等方面获得的利益。","0"));
        dao.add(new Word("259","differ","/'dɪfə/","vt. 使…相异；使…不同\nvi. 相异；意见分歧","His skin color differs from the others'.\n他的肤色和别人的都不一样。","[串记] differ  v.差异；不同\ndistinguish  v.区别，识别，辨别\ndifferent  adj.差异的，各种的\ndifference  n.差别","0"));
        dao.add(new Word("260","satisfy","/'sætɪsfaɪ/","vi. 令人满意；令人满足\nvt. 满足；说服，使相信；使满意，使高兴","The delicious pizza satisfied that boy.\n这个好吃的披萨大大地满足了那个小男孩。","[串记] satisfy  v.令人满意\nsatisfaction  n.满足，满意，乐事\nsatisfied  adj.感到满意的\nsatisfactory  adj.令人满意的；良好的","0"));

        dao.add(new Word("261","voluntary","/'vɒlənt(ə)rɪ/","adj. 自愿的；志愿的；自发的；故意的\nn. 志愿者；自愿行动","Giving blood is 100% voluntary: nobody will force you to do it.\n献血是百分之百自愿的，没人会强迫你去做。","[对比] voluntary/willing均有“自愿的”之意。\nvoluntary：侧重不受约束，行动不为其他影响所左右。\nwilling：着重自愿、令人愉快或急切地去行动。","0"));
        dao.add(new Word("262","crime","/kraɪm/","n. 罪行，犯罪；罪恶；犯罪活动\nvt. 控告……违反纪律","Those who commit crimes must be severely punished.\n那些罪犯必须受到严惩。","[串记] crime  n.罪行  vt.控告……违反纪律\ncriminal  adj.犯罪的，刑法的  n.罪犯\ncriminative  adj.控告的；使负罪的\ncriminological  adj.犯罪学的\ncriminology  n.犯罪学；刑事学","0"));
        dao.add(new Word("263","connect","/kə'nekt/","vt. 连接；联合；关连\nvi. 连接，连结；联合","Our on-line community connects us all to each other.\n我们的线上社区将我们所有人联系在一起。","[对比] connect/contact/chain均有“连接”之意。\nconnect：指两个事物的连接，以及由一件事联想到另一件事。\ncontact：多指用书信，交流联系交流。\nchain：指事物之间存在的联系，有约束关系。","0"));
        dao.add(new Word("264","detail","/'diːteɪl/","n. 细节，详情\nvt. 详述；选派\nvi. 画详图","When the leaf is seen up close, you can see a lot of fine details.\n近距离看树叶时，你可以看到很多的细节。","[串记] tail  n.尾巴  v.紧跟\ntailor  n.裁缝  v.做裁缝\nretail  n.零售  v.零售\ndetail  n.细节  vt.详述","0"));
        dao.add(new Word("265","intelligent","/ɪn'telɪdʒ(ə)nt/","adj. 智能的；聪明的；理解力强的","She can do very difficult math--what an intelligent girl!\n她能解出非常难的数学题，真是个聪明的女孩儿！","[串记] intellect  n.智力，理解力；知识分子\nintellectual  n.知识分子  adj.智力的；聪明的\nintellectualism  n.理智主义，知性主义\nintelligible  adj.可理解的；明了的","0"));
        dao.add(new Word("266","promise","/'prɒmɪs/","n. 许诺，允诺；希望\nvt. 允诺，许诺；给人以…的指望或希望\nvi. 许诺；有指望，有前途","I promise that I am telling you the truth.\n我保证我所言属实。","[串记] promise to do sth  答应做某事\npromise sth to sb  允诺给某人某物\npromise + that从句  答应，许诺","0"));
        dao.add(new Word("267","reliable","/rɪ'laɪəb(ə)l/","adj. 可靠的；可信赖的\nn. 可靠的人","I hope the guy holding this rope is reliable.\n我希望攥着绳子的这家伙是可靠的。","[串记] unreliable  adj.不可靠的；靠不住的\nreliability  n.可靠性\nrely  vi.依靠；信赖\nreliable  n.可靠的人  adj.可靠的；可信赖的","0"));
        dao.add(new Word("268","exposure","ɪk'spəʊʒə; ek-","n. 暴露；曝光；揭露；陈列","He almost died from exposure to cold temperatures.\n他差点因为长时间处于低温环境中而死掉。","[串记] expose  v.暴露，揭露\nexposure  n.暴露，揭露；(to)受到\nexposit  vt.揭示；显示\nexpository  adj.说明的；解释的\nexposition  n.博览会；阐述","0"));
        dao.add(new Word("269","locate","/lə(ʊ)'keɪt/","vt. 位于；查找…的地点\nvi. 定位；定居","The most important cities are located here, here and here.\n几个最重要的城市位于这里，这里，还有这里。","[串记] local  adj.当地的，本地的\nlocality  n.地区，地方，地点\nlocate  v.测定，找出...的位置\nlocation  n.位置，定位","0"));
        dao.add(new Word("270","criticism","'krɪtɪsɪz(ə)m","n. 批评；考证；苛求","You should expect a lot of criticism when starting a new job.\n开始一项新工作的时候，你就应该想到会受到很多批评。","[串记] self-criticism  自我批评\ncritic  n.评论家，批判者，挑剔的人\ncritical  adj.批评的，文艺评论的\ncriticize  v.批评；评论；责难","0"));

        dao.add(new Word("271","survivor","/sə'vaɪvə/","n. 幸存者；生还者；残存物","There were few survivors of the plane crash.\n这场空难几乎没有生还者。","[串记] survive  v.活下来，幸存\nsurviving  adj.继续存在的；未死的\nsurvival  n. 生存，残存物  adj. 救生的\nsurvivor  n.生还者，残存物","0"));
        dao.add(new Word("272","secondary","/'sek(ə)nd(ə)rɪ/","adj. 第二的；中等的；次要的；中级的\nn. 副手；代理人","He took the silver medal, which is secondary in importance.\n他取得了第二重要的银牌。","[串记] primary  adj.首要的\nsecondary  adj.次要的","0"));
        dao.add(new Word("273","suck","/sʌk/","vt. 吸吮；吸取\nvi. 吸吮；糟糕；巴结\nn. 吮吸","The little girl sucks her lollipop.\n这个小女孩吮吸她的棒棒糖。","[串记] suck  v.吸吮；吸取  n.吮吸\nsack  n.麻袋；开除  v.开除\nslack  adj.松(弛)的  n.松弛部分  v.懈怠","0"));
        dao.add(new Word("274","activity","/ækˈtɪvətɪ/","n. 活动；行动；活跃","Biking is an exercise activity.\n骑自行车是一种锻炼活动。","[串记] act  n.法案；一幕  v.扮演\naction  n.行动, 行为  vt.【法律】对…起诉\nactive  adj.积极的，能起作用的\nactivity  n.活动；行动；活跃","0"));
        dao.add(new Word("275","promote","/prə'məʊt/","vt. 促进；提升；推销；发扬\nvi. 成为王后或其他大于卒的子","She was very good at her job, so her boss promoted her to a higher position.\n她工作表现很棒，所以她的老板把她升到了更高的位置。","[串记] promote  v.促进，提升；发扬\nprompt  adj.迅速的  v.敦促\npropose  v.提议，求婚","0"));
        dao.add(new Word("276","approach","/ə'prəʊtʃ/","n. 方法；途径；接近\nvt. 接近；着手处理\nvi. 靠近","The elephants are approaching us.\n一群大象正在靠近我们。","[串记] proach  表示接近\napproach  n.方法，接近  v.接近\nreproach  v.责备，指责  n.指责","0"));
        dao.add(new Word("277","edition","/ɪ'dɪʃ(ə)n/","n.版，版本，版次","This is the newest edition of the book.\n这是这本书最新的版本了。","[串记] editor  n.编辑，编者\nedit  v.编辑，剪辑\nedition  n.版，版本，版次\nformat  n.版式  v.设计一个版式","0"));
        dao.add(new Word("278","complaint","/kəm'pleɪnt/","n. 抱怨；诉苦；疾病；委屈","My wife's complaints are usually about me.\n我老婆的抱怨通常都是关于我的。","[串记] explain  v.解释；说明\ncomplaint  n.抱怨，怨言，不满的缘由\ncomplain  v.抱怨，诉苦，申诉\ncompliment  n.恭维，问候  v.赞美，祝贺\ncompliance  n.遵守，依从；承诺","0"));
        dao.add(new Word("279","economics","/iːkə'nɒmɪks; ek-/","n. 经济学；国家的经济状况","We should have a deep knowledge of economics to understand changes in the global market.\n我们应该有深厚的经济学知识，才能理解全球市场的变化（形势）。","[对比] 共同释义：经济的，财务的\neconomic：除指经济的外，还表示经济上有收益的，有利可图的\neconomical：指节约的，精打细算的\nfinancial：指财政的，财务的，财力的\neconomy：作形容词用在名词前面，构成名词短语，含义相当于economical。","0"));
        dao.add(new Word("280","psychological","/saɪkə'lɒdʒɪk(ə)l/","adj. 心理的；心理学的；精神上的","A psychiatrist has to understand the psychological condition of his patient.\n心理医生必须理解病人心理方面（的问题）。","[串记] physics  物理学\nphilosophy  哲学\npsychology  心理学","0"));

        dao.add(new Word("281","concrete","/'kɒŋkriːt/","adj. 混凝土的；实在的，具体的；有形的\nvi. 凝结\nvi. 凝结\nn. 具体物；凝结物","Concrete is a very useful substance for making roads and buildings.\n建造道路和建筑中，水泥是一种非常有用的材料。","[串记] concrete  adj.具体的\ndiscrete  adj.离散的\ndiscrete mathematics  离散数学","0"));
        dao.add(new Word("282","evidence","/'evɪd(ə)ns/","n. 证据，证明；迹象；明显\nvt. 证明","Keep every piece of evidence to help us solve the crime.\n保存每一条证据以帮助我们侦破犯罪案件。","[对比] proof/evidence区别：\nproof：指足以直接证明某事为某事实的依据，侧重作为充分证据所导致的结果。\nevidence：在法律上指能起到证明作用的，在生活上指任何一样可证明某一件事的真实性的东西。","0"));
        dao.add(new Word("283","overseas","/əʊvə'siːz/","adv. 在海外，海外\nadj. 海外的，国外的","We export the goods overseas.\n我们把货物出口到海外。","[对比] overseas students  从国外回来的学生\nstudents overseas  到国外学习的学生","0"));
        dao.add(new Word("284","elaborate","/ɪ'læb(ə)rət/","adj. 精心制作的；详尽的；煞费苦心的\nvt. 精心制作；详细阐述；从简单成分合成（复杂有机物）\nvi. 详细描述；变复杂","The designs for the house are very elaborate; they took me days to draw.\n这栋房子的设计图非常精细，是我花了好多功夫画出来的。","[串记] elaboration  n.苦心经营，精巧；详细阐述\nelaborateness  n.尽心竭力\nelaborately  adv.精巧地；苦心经营地","0"));
        dao.add(new Word("285","failure","/'feɪljə/","n. 失败；故障；失败者；破产","If I can't increase sales, I'll be a failure!\n如果不能增加销售额，我就是一个失败者！","[串记] fail  v.失败，不及格\nfailed  adj.已失败的，不成功的\nfault  n.过失，错误  v.责备\nfalse  adj.错误的，虚伪的，伪造的","0"));
        dao.add(new Word("286","release","/rɪ'liːs/","vt. 释放；发射；让与；允许发表\nn. 释放；发布；让与","She releases the dove as a symbol of peace.\n她放飞了白鸽，作为和平的象征。","[对比] free/liberate/release均有“释放，自由”之意。\nfree：指不再受任何约束，阻碍和压迫，完全可按自己的意志行动。\nliberate：常指从束缚和压迫中解放出来，强调获得最终的解放。\nrelease：侧重指放松限制，解除监禁或免除义务。","0"));
        dao.add(new Word("287","reasonable","/'riːz(ə)nəb(ə)l/","adj. 合理的，公道的；通情达理的","It's not reasonable to carry so many books around!\n拿着这么多书到处走，这不合适吧！","[联想] reason（原因）+ able（能够）\n拿别人的东西要有原因的=合理的。","0"));
        dao.add(new Word("288","retain","/rɪ'teɪn/","vt. 保持；雇；记住","Camels have fatty humps that allow them to retain water.\n骆驼身上充满脂肪的驼峰可以帮它们储存水。","[串记] remain  v.剩下，余留，保持不变\nretain  v.保持，保留，保存\ncontain  v.包含，容纳；遏制\nmaintain  v.维持，赡养，维修","0"));
        dao.add(new Word("289","shortage","/'ʃɔːtɪdʒ/","n. 缺乏，缺少；不足","I have a severe cash shortage right now--could you lend me some money?\n我现在非常缺钱，你可以借我点钱吗？","[串记] defect  n.欠缺，缺点  v.背叛\nshortcoming  n.短处，缺点\nweakness  n.虚弱；软弱；弱点\ndeficiency  n.缺乏，不足；缺陷","0"));
        dao.add(new Word("290","multiply","/'mʌltɪplaɪ/","vt. 乘；使增加；使繁殖；使相乘\nvi. 乘；繁殖；增加\nadv. 多样地；复合地\nadj. 多层的；多样的","10 multiplied by 8 is 80.\n10乘以8等于80。","[串记] plus=add 加+\nminus=subtract 减-\nmultiply=times 乘×\ndivide（into）除÷","0"));

        dao.add(new Word("291","assemble","/ə'semb(ə)l/","vt. 集合，聚集；装配；收集\nvi. 集合，聚集","The factory assembles cars. \n这家工厂负责装配车辆。","[串记] semblance  n.相似；外表\nassemble  v.装配(机器等)；集合\nresemblance  n.相似，形似\ndissemble  v.掩饰；假装","0"));
        dao.add(new Word("292","extension","/ɪk'stenʃ(ə)n; ek-/","n. 延长；延期；扩大；伸展；电话分机","This extension ladder can extend up to 50 meters.\n这个可伸展的楼梯可以展开成50米长。","[串记] expand  vi. 膨胀，展开，扩大\nexpanse  n.宽阔；广阔的区域；苍天\nexpend  v.消费，用尽\nextend  v.延伸，延长，扩展\nextension  n.延长部分，伸展","0"));
        dao.add(new Word("293","depress","/dɪ'pres/","vt. 压抑；使沮丧；使萧条","School tends to depress the boy; it always makes him sad.\n学校渐渐让这个男孩儿觉得压抑，（学校）总是让他觉得很难过。","[串记] impress（压在里面） v.使印象深刻\ndepress（往下压） v.降低，使消沉\noppress（加深程度） v.压迫\nsuppress（由上往下压）v.镇压","0"));
        dao.add(new Word("294","communication","/kəmjuːnɪ'keɪʃ(ə)n/","n. 通讯，[通信] 通信；交流；信函","Cell phones make communication easier than ever.\n手机使得通讯比过去更容易。","[串记] communication  n.传达，交际，通讯\ncommunity  n.社区，团体\ncommunicate  v.通讯；传达；沟通","0"));
        dao.add(new Word("295","initial","/ɪ'nɪʃəl/","adj. 最初的；字首的\nvt. 用姓名的首字母签名\nn. 词首大写字母","The initial letter of \"aardvark\" is \"A\".\n“aardvark（非洲食蚁兽）”的首字母是“a”。","[串记] initial  n.首字母  adj.开始的\ninitiation  n.启蒙，传授；开始\ninitiative  n.主动的行动，主动性\ninitialize  vt.初始化","0"));
        dao.add(new Word("296","enterprise","/'entəpraɪz/","n. 企业；事业；进取心；事业心","The businessmen begin a new enterprise.\n商人开办一家新公司。","[串记] firm  较小的公司\ncompany  公司\ncorporate  较大的公司\nenterprise  大集团","0"));
        dao.add(new Word("297","reward","/rɪ'wɔːd/","n. [劳经] 报酬；报答；酬谢\nvt. [劳经] 奖励；奖赏","My reward for winning the race was a big trophy.\n我赢得比赛的奖品是一个大奖杯。","[串记] ward n.病房 v.守护，收容\nreward n.报酬，报答 v.酬谢\naward n.奖赏 v.判定\naware v.意识到","0"));
        dao.add(new Word("298","particular","/pəˈtɪkjʊlə(r)/","adj. 特别的；详细的；独有的；挑剔的\nn. 详细说明；个别项目","I chose five particular people out of the crowd.\n我从人群中选出了五个与众不同的人。","[对比] particular/especial/special均有“特殊的”之意。\nparticular：强调事物的独特性。\nespecial：强调特别的、非同寻常的。\nspecial：强调专门或特意的。","0"));
        dao.add(new Word("299","considerable","/kən'sɪd(ə)rəb(ə)l/","adj. 相当大的；重要的，值得考虑的","His strength is considerable; he exercises every day. \n他的力气相当大，（因为）他每天都锻炼。","[串记] consider  v.认为；考虑\nconsiderate  adj.考虑周到的；体贴的\nconsiderable  adj.相当大的，重要的\nconsideration  n.考虑，思考","0"));
        dao.add(new Word("300","criticise","/'krɪtɪ,saɪz/","vt. 批评；吹毛求疵；非难\nvi. 批评；吹毛求疵；非难","He criticised me for not doing my work very well.\n他因为我工作没有做好而批评我。","[串记] self-criticism  自我批评\ncritic  n.评论家，批判者，挑剔的人\ncritical  adj.批评的，文艺评论的\ncriticize  v.批评；评论；责难","0"));

        dao.add(new Word("301","instruct","/ɪn'strʌkt/","vt. 指导；通知；命令；教授","My mom instructs me how to play golf.\n我妈妈教我怎么打高尔夫。","[串记] instruct  v.命令，教授，通知\nconstruct  v.建造，建设，构筑\ninstruction  n.教学；指示；指导\ninstrument  n.仪器，工具，乐器","0"));
        dao.add(new Word("302","reflect","/rɪ'flekt/","vt. 反映；反射，照出；表达；显示;反省\nvi. 反射，映现；深思","It's so beautiful how the water reflects the sky. \n天空倒映在湖面上，真是太美了！","[对比] deliberate/meditate/reflect均有“思考，判断”之意。\ndeliberate：指缓慢、按部就班地作仔细而认真地思考或判断。\nmeditate：指认真地长时间集中精力进行思考。\nreflect：指认真而冷静地反复地思考某个问题，尤指对已经发生事情的思索。","0"));
        dao.add(new Word("303","emphasis","/'emfəsɪs/","n. 重点；强调；加强语气","In his speech, he put emphasis on our need to work harder.\n在他的讲话中，他把重点放在了我们应该更加努力地工作上。","[串记] emphasis  n.强调，重点，重要性\nemphasise  v.强调\nemphasize  v.强调","0"));
        dao.add(new Word("304","infer","/ɪn'fɜː/","vt. 推断；推论\nvi. 推断；作出推论","I infer from the lock that data security is important to you.\n从这个锁我推断数据安全对你来说很重要。","[串记] infer  v.做出推论\noffer  n.提供; 出价  v.提议\nconfer  v.协商；授予\nrefer  v.参看，涉及，归因于\ndefer  v.延期","0"));
        dao.add(new Word("305","plug","/plʌg/","n. 插头；塞子；栓\nvi. 塞住；用插头将与电源接通\nvt. 插入；塞住；接插头","I infer from the lock that data security is important to you.\n从这个锁我推断数据安全对你来说很重要。","[串记] rug  n.(小)地毯；围毯\ndrug  n.药物，毒品  v.下麻药\nbug  n.错误，故障  v.除虫\nhug  v.紧抱；拥抱  n.拥抱\ntug  v.用力拖(或拉)  n.猛拉","0"));
        dao.add(new Word("306","contrary","/'kɒntrərɪ/","adj. 相反的；对立的\nadv. 相反地\nn. 相反；反面","My sister is so contrary - she always disagrees with whatever I say!\n我妹妹太叛逆了，我说什么她都不赞同。","[串记] contract  n.合同，契约  v.订合同\ncontrast  v.(with)使与...对比  n.对照\ncontrastive  adj.对比的\ncontradict  v.反驳；否定","0"));
        dao.add(new Word("307","chip","/tʃɪp/","vt. 削，凿；削成碎片\nvi. 剥落；碎裂\nn. [电子] 芯片；筹码；碎片；(食物的) 小片; 薄片","There are many wood chips on the floor.\n地板上有很多木屑。","[联想] 每次吃薯片（chips）都是碎片（chip）让我忍不住想把送快递的小伙子（chap）削（chip）/剁（chop）/剪（clip）成排骨（chop）。","0"));
        dao.add(new Word("308","sketch","/sketʃ/","n. 素描；略图；梗概\nvt. 画素描或速写\nvi. 画素描或速写","This is just a brief sketch of what I think the machine should look like.\n这只是一个简要的草图，画的是我想象中这个机器的样子。","[串记] sketch  n.梗概，素描  v. 速写\nstretch  v.延伸，伸长  n.伸展\nsnatch  v.强夺，攫取  n.片断\nscratch  v.划破，擦伤  n.抓痕","0"));
        dao.add(new Word("309","qualify","/'kwɒlɪfaɪ/","vt. 限制；使具有资格；证明…合格\nvi. 取得资格，有资格","Take this test first, and we'll see if you qualify for the job.\n先做这个测验，我们要看下你是否有资格做这份工作。","[串记] quality  n.特性; 品性  adj. 优质的\nqualitative  adj.(性)质的，定性的\nqualification  n.资格证明，合格证书\nquantity  n.量，总数，大量","0"));
        dao.add(new Word("310","community","/kəˈmju:nətɪ/","n. 社区；[生态] 群落；共同体；团体","Our village is a happy community where we all like to help our neighbors.\n因为我们邻里间都喜欢相互帮助，所以我们的社区很和谐。","[串记] communication  n.传达，交际，通讯\ncommunity  n.社区，团体\ncommunicate  v.通讯；传达；沟通","0"));

        dao.add(new Word("311","process","/prəˈses;(for n.)ˈprəʊses/","vt. 处理；加工\nn. 过程，进行；方法，步骤；作用；程序；推移\nvi. 列队前进\nadj. 经过特殊加工（或处理）的","This project has been a long process.\n这个项目经历了一个很长的流程。","[联想] possess  v.拥有，占有\nprogress  n.进步；前进，进展\nprocess  n.过程，工序  v.加工\nsuccess  n.成功，成就","0"));
        dao.add(new Word("312","publish","/'pʌblɪʃ/","vt. 出版；发表；公布\nvi. 出版；发行；刊印","They'll publish my book both electronically and in print.\n他们会出版我的书，电子版和印刷版都有。","[对比] announce/proclaim/publish均有“宣布，公开”之意。\nannounce：多指首次宣布大家感兴趣或者可满足大家好奇心的事情。\nproclaim：指官方宣布重大事情。\npublish：专指通过报刊或其他媒介向公众公布事情。","0"));
        dao.add(new Word("313","inspire","/ɪn'spaɪə/","vt. 激发；鼓舞；启示；产生；使生灵感","Seeing the sunrise on the mountain top really inspired me.\n看着太阳从山顶升起对我是很大的激励。","[串记] respire  v.呼吸\nexpire  v.期满，断气，死亡\ninspire  v.使生灵感；启示；激发\naspire  vi.热望，渴望\nconspire  v.共谋，密谋策划；协力","0"));
        dao.add(new Word("314","reverse","/rɪ'vɜːs/","n. 背面；相反；倒退；失败\nvt. 颠倒；倒转\nadj. 反面的；颠倒的；反身的\nvi. 倒退；逆叫","She can reverse her car into a parking space.\n她可以把她的车倒进车位。","[串记] persevere  v.坚持，不屈不挠\npreserve  v.保护，保存\nconserve  n.蜜饯  vt.保藏\nperceive  v.意识到，察觉，发觉","0"));
        dao.add(new Word("315","panic","/'pænɪk/","n. 恐慌，惊慌；大恐慌\nadj. 恐慌的；没有理由的\nvt. 使恐慌\nvi. 十分惊慌","After she fell she reached for her shoes in a panic.\n跌倒之后她慌张地捡起了鞋子。","[对比] alarm/fear/panic区别：\nalarm：强调突然意识到有危险而产生的恐惧心理。\nfear：侧重指面临危险或灾祸时内心所引起的恐惧心情。\npanic：常指因突如其来的外界威胁使人群出现惊慌、恐惧或混乱。","0"));
        dao.add(new Word("316","stainless","/'steɪnlɪs/","adj. 不锈的；纯洁的，未被玷污的；无瑕疵的","Spoons and forks are made of stainless steel so they are strong and easy to clean.\n勺子和叉子是由不锈钢制造的,所以它们又硬又易于清洁。","[串记] stainless  adj.不锈的\nthinness  n.薄；瘦；细\nheadless  adj.无头的","0"));
        dao.add(new Word("317","strengthen","/'streŋθ(ə)n; -ŋkθ(ə)n/","vt. 加强；巩固\nvi. 变强；变坚挺","The woman lifts weights to strengthen her arms.\n这个女人通过举重来强健手臂。","[联想] strong（强壮）then（然后）\n你变强之后就可以加强巩固了。","0"));
        dao.add(new Word("318","previous","/'priːvɪəs/","adj. 以前的；早先的；过早的\nadv. 在先；在…以前","Press this button to go back to the previous page. \n按这个按钮，回到上一页。","[对比]  previous/foregoing/precedent均有“先前的”之意。\nprevious：指时间上、顺序上较早的，或指正在谈论的某事的前一个。\nforegoing：指前所述的，是following的反义词。\nprecedent：特指时间和地位上紧接在前。","0"));
        dao.add(new Word("319","monitor","/'mɒnɪtə/","n. 监视器；监听器；监控器；显示屏；班长\nvt. 监控","I want a new, flat screen computer monitor.\n我想要一个新的纯平电脑显示器。","[联想] 班长（monitor）是老师安排监视（monitor）我们的。","0"));
        dao.add(new Word("320","eventually","/ɪ'ventʃʊəlɪ/","adv. 最后，终于","University was difficult for me, but I graduated eventually.\n大学对我来说是困难的，但是我终于毕业了。","[串记] finally/eventually/lastly均有“最后的”之意。\nfinally：指一系列事情的最后结局。\neventually：侧重于动作或行为的结果。\nlastly：指连续顺序的最后，通常用来列举事情的场合。","0"));
        dao.add(new Word("321","complain","/kəm'pleɪn/","vi.抱怨，诉苦，申诉，控诉\nvt.诉说，申诉，控诉","\"This math problem is so difficult；it make my head hurt！\"she complained.\n“这道数学题太难了，我头疼死了！”她抱怨道。","[串记] explain  v.解释；说明\ncomplaint  n.抱怨，怨言，不满的缘由\ncomplain  v.抱怨，诉苦，申诉\ncompliment  n.恭维，问候  v.赞美，祝贺\ncompliance  n.遵守，依从；承诺","0"));

    }
}
